package com.nantian.dao;

import java.math.BigDecimal;
import java.util.Date;

public class TCustmorBasic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.CUSTMOR_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String custmorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.CUSTMOR_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String custmorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.CUSTMOR_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String custmorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.ORG_CODE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.BUSI_LIENCE_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String busiLienceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.OWN_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String ownType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.ORG_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String orgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.IND_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String indNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.ENTE_SIZE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String enteSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.REG_AMT
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private BigDecimal regAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.POST_CODE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.ADDR
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.CONN_PHONE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String connPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.CONN_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String connName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.RESP_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String respName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.ACC_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String accNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.BANK_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String bankType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.BANK_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.NATIONAL_LIENCE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String nationalLience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.PROPERTY_TAX_LIENCE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String propertyTaxLience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.CREDIT
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.REMB_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String rembNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.OPERATOR
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.OPR_DATE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private Date oprDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.STATUS
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.IS_VALID
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_BASIC.MARK
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.CUSTMOR_NO
     *
     * @return the value of T_CUSTMOR_BASIC.CUSTMOR_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getCustmorNo() {
        return custmorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.CUSTMOR_NO
     *
     * @param custmorNo the value for T_CUSTMOR_BASIC.CUSTMOR_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setCustmorNo(String custmorNo) {
        this.custmorNo = custmorNo == null ? null : custmorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.CUSTMOR_NAME
     *
     * @return the value of T_CUSTMOR_BASIC.CUSTMOR_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getCustmorName() {
        return custmorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.CUSTMOR_NAME
     *
     * @param custmorName the value for T_CUSTMOR_BASIC.CUSTMOR_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setCustmorName(String custmorName) {
        this.custmorName = custmorName == null ? null : custmorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.CUSTMOR_TYPE
     *
     * @return the value of T_CUSTMOR_BASIC.CUSTMOR_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getCustmorType() {
        return custmorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.CUSTMOR_TYPE
     *
     * @param custmorType the value for T_CUSTMOR_BASIC.CUSTMOR_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setCustmorType(String custmorType) {
        this.custmorType = custmorType == null ? null : custmorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.ORG_CODE
     *
     * @return the value of T_CUSTMOR_BASIC.ORG_CODE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.ORG_CODE
     *
     * @param orgCode the value for T_CUSTMOR_BASIC.ORG_CODE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.BUSI_LIENCE_NO
     *
     * @return the value of T_CUSTMOR_BASIC.BUSI_LIENCE_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getBusiLienceNo() {
        return busiLienceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.BUSI_LIENCE_NO
     *
     * @param busiLienceNo the value for T_CUSTMOR_BASIC.BUSI_LIENCE_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setBusiLienceNo(String busiLienceNo) {
        this.busiLienceNo = busiLienceNo == null ? null : busiLienceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.OWN_TYPE
     *
     * @return the value of T_CUSTMOR_BASIC.OWN_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getOwnType() {
        return ownType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.OWN_TYPE
     *
     * @param ownType the value for T_CUSTMOR_BASIC.OWN_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setOwnType(String ownType) {
        this.ownType = ownType == null ? null : ownType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.ORG_TYPE
     *
     * @return the value of T_CUSTMOR_BASIC.ORG_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.ORG_TYPE
     *
     * @param orgType the value for T_CUSTMOR_BASIC.ORG_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType == null ? null : orgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.IND_NO
     *
     * @return the value of T_CUSTMOR_BASIC.IND_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getIndNo() {
        return indNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.IND_NO
     *
     * @param indNo the value for T_CUSTMOR_BASIC.IND_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setIndNo(String indNo) {
        this.indNo = indNo == null ? null : indNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.ENTE_SIZE
     *
     * @return the value of T_CUSTMOR_BASIC.ENTE_SIZE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getEnteSize() {
        return enteSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.ENTE_SIZE
     *
     * @param enteSize the value for T_CUSTMOR_BASIC.ENTE_SIZE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setEnteSize(String enteSize) {
        this.enteSize = enteSize == null ? null : enteSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.REG_AMT
     *
     * @return the value of T_CUSTMOR_BASIC.REG_AMT
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public BigDecimal getRegAmt() {
        return regAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.REG_AMT
     *
     * @param regAmt the value for T_CUSTMOR_BASIC.REG_AMT
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setRegAmt(BigDecimal regAmt) {
        this.regAmt = regAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.POST_CODE
     *
     * @return the value of T_CUSTMOR_BASIC.POST_CODE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.POST_CODE
     *
     * @param postCode the value for T_CUSTMOR_BASIC.POST_CODE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.ADDR
     *
     * @return the value of T_CUSTMOR_BASIC.ADDR
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.ADDR
     *
     * @param addr the value for T_CUSTMOR_BASIC.ADDR
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.CONN_PHONE
     *
     * @return the value of T_CUSTMOR_BASIC.CONN_PHONE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getConnPhone() {
        return connPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.CONN_PHONE
     *
     * @param connPhone the value for T_CUSTMOR_BASIC.CONN_PHONE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setConnPhone(String connPhone) {
        this.connPhone = connPhone == null ? null : connPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.CONN_NAME
     *
     * @return the value of T_CUSTMOR_BASIC.CONN_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getConnName() {
        return connName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.CONN_NAME
     *
     * @param connName the value for T_CUSTMOR_BASIC.CONN_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setConnName(String connName) {
        this.connName = connName == null ? null : connName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.RESP_NAME
     *
     * @return the value of T_CUSTMOR_BASIC.RESP_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getRespName() {
        return respName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.RESP_NAME
     *
     * @param respName the value for T_CUSTMOR_BASIC.RESP_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setRespName(String respName) {
        this.respName = respName == null ? null : respName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.ACC_NO
     *
     * @return the value of T_CUSTMOR_BASIC.ACC_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.ACC_NO
     *
     * @param accNo the value for T_CUSTMOR_BASIC.ACC_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setAccNo(String accNo) {
        this.accNo = accNo == null ? null : accNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.BANK_TYPE
     *
     * @return the value of T_CUSTMOR_BASIC.BANK_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.BANK_TYPE
     *
     * @param bankType the value for T_CUSTMOR_BASIC.BANK_TYPE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.BANK_NAME
     *
     * @return the value of T_CUSTMOR_BASIC.BANK_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.BANK_NAME
     *
     * @param bankName the value for T_CUSTMOR_BASIC.BANK_NAME
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.NATIONAL_LIENCE
     *
     * @return the value of T_CUSTMOR_BASIC.NATIONAL_LIENCE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getNationalLience() {
        return nationalLience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.NATIONAL_LIENCE
     *
     * @param nationalLience the value for T_CUSTMOR_BASIC.NATIONAL_LIENCE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setNationalLience(String nationalLience) {
        this.nationalLience = nationalLience == null ? null : nationalLience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.PROPERTY_TAX_LIENCE
     *
     * @return the value of T_CUSTMOR_BASIC.PROPERTY_TAX_LIENCE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getPropertyTaxLience() {
        return propertyTaxLience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.PROPERTY_TAX_LIENCE
     *
     * @param propertyTaxLience the value for T_CUSTMOR_BASIC.PROPERTY_TAX_LIENCE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setPropertyTaxLience(String propertyTaxLience) {
        this.propertyTaxLience = propertyTaxLience == null ? null : propertyTaxLience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.CREDIT
     *
     * @return the value of T_CUSTMOR_BASIC.CREDIT
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.CREDIT
     *
     * @param credit the value for T_CUSTMOR_BASIC.CREDIT
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setCredit(String credit) {
        this.credit = credit == null ? null : credit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.REMB_NO
     *
     * @return the value of T_CUSTMOR_BASIC.REMB_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getRembNo() {
        return rembNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.REMB_NO
     *
     * @param rembNo the value for T_CUSTMOR_BASIC.REMB_NO
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setRembNo(String rembNo) {
        this.rembNo = rembNo == null ? null : rembNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.OPERATOR
     *
     * @return the value of T_CUSTMOR_BASIC.OPERATOR
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.OPERATOR
     *
     * @param operator the value for T_CUSTMOR_BASIC.OPERATOR
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.OPR_DATE
     *
     * @return the value of T_CUSTMOR_BASIC.OPR_DATE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public Date getOprDate() {
        return oprDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.OPR_DATE
     *
     * @param oprDate the value for T_CUSTMOR_BASIC.OPR_DATE
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setOprDate(Date oprDate) {
        this.oprDate = oprDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.STATUS
     *
     * @return the value of T_CUSTMOR_BASIC.STATUS
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.STATUS
     *
     * @param status the value for T_CUSTMOR_BASIC.STATUS
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.IS_VALID
     *
     * @return the value of T_CUSTMOR_BASIC.IS_VALID
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.IS_VALID
     *
     * @param isValid the value for T_CUSTMOR_BASIC.IS_VALID
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_BASIC.MARK
     *
     * @return the value of T_CUSTMOR_BASIC.MARK
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_BASIC.MARK
     *
     * @param mark the value for T_CUSTMOR_BASIC.MARK
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_BASIC
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custmorNo=").append(custmorNo);
        sb.append(", custmorName=").append(custmorName);
        sb.append(", custmorType=").append(custmorType);
        sb.append(", orgCode=").append(orgCode);
        sb.append(", busiLienceNo=").append(busiLienceNo);
        sb.append(", ownType=").append(ownType);
        sb.append(", orgType=").append(orgType);
        sb.append(", indNo=").append(indNo);
        sb.append(", enteSize=").append(enteSize);
        sb.append(", regAmt=").append(regAmt);
        sb.append(", postCode=").append(postCode);
        sb.append(", addr=").append(addr);
        sb.append(", connPhone=").append(connPhone);
        sb.append(", connName=").append(connName);
        sb.append(", respName=").append(respName);
        sb.append(", accNo=").append(accNo);
        sb.append(", bankType=").append(bankType);
        sb.append(", bankName=").append(bankName);
        sb.append(", nationalLience=").append(nationalLience);
        sb.append(", propertyTaxLience=").append(propertyTaxLience);
        sb.append(", credit=").append(credit);
        sb.append(", rembNo=").append(rembNo);
        sb.append(", operator=").append(operator);
        sb.append(", oprDate=").append(oprDate);
        sb.append(", status=").append(status);
        sb.append(", isValid=").append(isValid);
        sb.append(", mark=").append(mark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_BASIC
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCustmorBasic other = (TCustmorBasic) that;
        return (this.getCustmorNo() == null ? other.getCustmorNo() == null : this.getCustmorNo().equals(other.getCustmorNo()))
            && (this.getCustmorName() == null ? other.getCustmorName() == null : this.getCustmorName().equals(other.getCustmorName()))
            && (this.getCustmorType() == null ? other.getCustmorType() == null : this.getCustmorType().equals(other.getCustmorType()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getBusiLienceNo() == null ? other.getBusiLienceNo() == null : this.getBusiLienceNo().equals(other.getBusiLienceNo()))
            && (this.getOwnType() == null ? other.getOwnType() == null : this.getOwnType().equals(other.getOwnType()))
            && (this.getOrgType() == null ? other.getOrgType() == null : this.getOrgType().equals(other.getOrgType()))
            && (this.getIndNo() == null ? other.getIndNo() == null : this.getIndNo().equals(other.getIndNo()))
            && (this.getEnteSize() == null ? other.getEnteSize() == null : this.getEnteSize().equals(other.getEnteSize()))
            && (this.getRegAmt() == null ? other.getRegAmt() == null : this.getRegAmt().equals(other.getRegAmt()))
            && (this.getPostCode() == null ? other.getPostCode() == null : this.getPostCode().equals(other.getPostCode()))
            && (this.getAddr() == null ? other.getAddr() == null : this.getAddr().equals(other.getAddr()))
            && (this.getConnPhone() == null ? other.getConnPhone() == null : this.getConnPhone().equals(other.getConnPhone()))
            && (this.getConnName() == null ? other.getConnName() == null : this.getConnName().equals(other.getConnName()))
            && (this.getRespName() == null ? other.getRespName() == null : this.getRespName().equals(other.getRespName()))
            && (this.getAccNo() == null ? other.getAccNo() == null : this.getAccNo().equals(other.getAccNo()))
            && (this.getBankType() == null ? other.getBankType() == null : this.getBankType().equals(other.getBankType()))
            && (this.getBankName() == null ? other.getBankName() == null : this.getBankName().equals(other.getBankName()))
            && (this.getNationalLience() == null ? other.getNationalLience() == null : this.getNationalLience().equals(other.getNationalLience()))
            && (this.getPropertyTaxLience() == null ? other.getPropertyTaxLience() == null : this.getPropertyTaxLience().equals(other.getPropertyTaxLience()))
            && (this.getCredit() == null ? other.getCredit() == null : this.getCredit().equals(other.getCredit()))
            && (this.getRembNo() == null ? other.getRembNo() == null : this.getRembNo().equals(other.getRembNo()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getOprDate() == null ? other.getOprDate() == null : this.getOprDate().equals(other.getOprDate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getMark() == null ? other.getMark() == null : this.getMark().equals(other.getMark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_BASIC
     *
     * @mbg.generated Wed Oct 25 12:32:21 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCustmorNo() == null) ? 0 : getCustmorNo().hashCode());
        result = prime * result + ((getCustmorName() == null) ? 0 : getCustmorName().hashCode());
        result = prime * result + ((getCustmorType() == null) ? 0 : getCustmorType().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getBusiLienceNo() == null) ? 0 : getBusiLienceNo().hashCode());
        result = prime * result + ((getOwnType() == null) ? 0 : getOwnType().hashCode());
        result = prime * result + ((getOrgType() == null) ? 0 : getOrgType().hashCode());
        result = prime * result + ((getIndNo() == null) ? 0 : getIndNo().hashCode());
        result = prime * result + ((getEnteSize() == null) ? 0 : getEnteSize().hashCode());
        result = prime * result + ((getRegAmt() == null) ? 0 : getRegAmt().hashCode());
        result = prime * result + ((getPostCode() == null) ? 0 : getPostCode().hashCode());
        result = prime * result + ((getAddr() == null) ? 0 : getAddr().hashCode());
        result = prime * result + ((getConnPhone() == null) ? 0 : getConnPhone().hashCode());
        result = prime * result + ((getConnName() == null) ? 0 : getConnName().hashCode());
        result = prime * result + ((getRespName() == null) ? 0 : getRespName().hashCode());
        result = prime * result + ((getAccNo() == null) ? 0 : getAccNo().hashCode());
        result = prime * result + ((getBankType() == null) ? 0 : getBankType().hashCode());
        result = prime * result + ((getBankName() == null) ? 0 : getBankName().hashCode());
        result = prime * result + ((getNationalLience() == null) ? 0 : getNationalLience().hashCode());
        result = prime * result + ((getPropertyTaxLience() == null) ? 0 : getPropertyTaxLience().hashCode());
        result = prime * result + ((getCredit() == null) ? 0 : getCredit().hashCode());
        result = prime * result + ((getRembNo() == null) ? 0 : getRembNo().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getOprDate() == null) ? 0 : getOprDate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getMark() == null) ? 0 : getMark().hashCode());
        return result;
    }
}