package com.nantian.dao;

import java.math.BigDecimal;
import java.util.Date;

public class TCustmorCredit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.ID
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.T_CUSTMOR_NO
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private String tCustmorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.PER_AMT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private String perAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.BG_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private Date bgDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.END_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.ACT_AMT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private BigDecimal actAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.STATUS
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.OPERATOR
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.OPR_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private Date oprDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.CURR
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private String curr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.SPENT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private BigDecimal spent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.IS_VALID
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CUSTMOR_CREDIT.MARK
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.ID
     *
     * @return the value of T_CUSTMOR_CREDIT.ID
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.ID
     *
     * @param id the value for T_CUSTMOR_CREDIT.ID
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.T_CUSTMOR_NO
     *
     * @return the value of T_CUSTMOR_CREDIT.T_CUSTMOR_NO
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public String gettCustmorNo() {
        return tCustmorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.T_CUSTMOR_NO
     *
     * @param tCustmorNo the value for T_CUSTMOR_CREDIT.T_CUSTMOR_NO
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void settCustmorNo(String tCustmorNo) {
        this.tCustmorNo = tCustmorNo == null ? null : tCustmorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.PER_AMT
     *
     * @return the value of T_CUSTMOR_CREDIT.PER_AMT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public String getPerAmt() {
        return perAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.PER_AMT
     *
     * @param perAmt the value for T_CUSTMOR_CREDIT.PER_AMT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setPerAmt(String perAmt) {
        this.perAmt = perAmt == null ? null : perAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.BG_DATE
     *
     * @return the value of T_CUSTMOR_CREDIT.BG_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public Date getBgDate() {
        return bgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.BG_DATE
     *
     * @param bgDate the value for T_CUSTMOR_CREDIT.BG_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setBgDate(Date bgDate) {
        this.bgDate = bgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.END_DATE
     *
     * @return the value of T_CUSTMOR_CREDIT.END_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.END_DATE
     *
     * @param endDate the value for T_CUSTMOR_CREDIT.END_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.ACT_AMT
     *
     * @return the value of T_CUSTMOR_CREDIT.ACT_AMT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public BigDecimal getActAmt() {
        return actAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.ACT_AMT
     *
     * @param actAmt the value for T_CUSTMOR_CREDIT.ACT_AMT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setActAmt(BigDecimal actAmt) {
        this.actAmt = actAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.STATUS
     *
     * @return the value of T_CUSTMOR_CREDIT.STATUS
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.STATUS
     *
     * @param status the value for T_CUSTMOR_CREDIT.STATUS
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.OPERATOR
     *
     * @return the value of T_CUSTMOR_CREDIT.OPERATOR
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.OPERATOR
     *
     * @param operator the value for T_CUSTMOR_CREDIT.OPERATOR
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.OPR_DATE
     *
     * @return the value of T_CUSTMOR_CREDIT.OPR_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public Date getOprDate() {
        return oprDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.OPR_DATE
     *
     * @param oprDate the value for T_CUSTMOR_CREDIT.OPR_DATE
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setOprDate(Date oprDate) {
        this.oprDate = oprDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.CURR
     *
     * @return the value of T_CUSTMOR_CREDIT.CURR
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public String getCurr() {
        return curr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.CURR
     *
     * @param curr the value for T_CUSTMOR_CREDIT.CURR
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setCurr(String curr) {
        this.curr = curr == null ? null : curr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.SPENT
     *
     * @return the value of T_CUSTMOR_CREDIT.SPENT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public BigDecimal getSpent() {
        return spent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.SPENT
     *
     * @param spent the value for T_CUSTMOR_CREDIT.SPENT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setSpent(BigDecimal spent) {
        this.spent = spent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.IS_VALID
     *
     * @return the value of T_CUSTMOR_CREDIT.IS_VALID
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.IS_VALID
     *
     * @param isValid the value for T_CUSTMOR_CREDIT.IS_VALID
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CUSTMOR_CREDIT.MARK
     *
     * @return the value of T_CUSTMOR_CREDIT.MARK
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CUSTMOR_CREDIT.MARK
     *
     * @param mark the value for T_CUSTMOR_CREDIT.MARK
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tCustmorNo=").append(tCustmorNo);
        sb.append(", perAmt=").append(perAmt);
        sb.append(", bgDate=").append(bgDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", actAmt=").append(actAmt);
        sb.append(", status=").append(status);
        sb.append(", operator=").append(operator);
        sb.append(", oprDate=").append(oprDate);
        sb.append(", curr=").append(curr);
        sb.append(", spent=").append(spent);
        sb.append(", isValid=").append(isValid);
        sb.append(", mark=").append(mark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCustmorCredit other = (TCustmorCredit) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.gettCustmorNo() == null ? other.gettCustmorNo() == null : this.gettCustmorNo().equals(other.gettCustmorNo()))
            && (this.getPerAmt() == null ? other.getPerAmt() == null : this.getPerAmt().equals(other.getPerAmt()))
            && (this.getBgDate() == null ? other.getBgDate() == null : this.getBgDate().equals(other.getBgDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getActAmt() == null ? other.getActAmt() == null : this.getActAmt().equals(other.getActAmt()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getOprDate() == null ? other.getOprDate() == null : this.getOprDate().equals(other.getOprDate()))
            && (this.getCurr() == null ? other.getCurr() == null : this.getCurr().equals(other.getCurr()))
            && (this.getSpent() == null ? other.getSpent() == null : this.getSpent().equals(other.getSpent()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getMark() == null ? other.getMark() == null : this.getMark().equals(other.getMark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((gettCustmorNo() == null) ? 0 : gettCustmorNo().hashCode());
        result = prime * result + ((getPerAmt() == null) ? 0 : getPerAmt().hashCode());
        result = prime * result + ((getBgDate() == null) ? 0 : getBgDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getActAmt() == null) ? 0 : getActAmt().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getOprDate() == null) ? 0 : getOprDate().hashCode());
        result = prime * result + ((getCurr() == null) ? 0 : getCurr().hashCode());
        result = prime * result + ((getSpent() == null) ? 0 : getSpent().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getMark() == null) ? 0 : getMark().hashCode());
        return result;
    }
}