package com.nantian.dao;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.math.BigDecimal;
import java.util.List;

public interface TCustmorCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    long countByExample(TCustmorCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    int deleteByExample(TCustmorCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    int insert(TCustmorCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    int insertSelective(TCustmorCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    List<TCustmorCredit> selectByExampleWithRowbounds(TCustmorCreditExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    List<TCustmorCredit> selectByExample(TCustmorCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    TCustmorCredit selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") TCustmorCredit record, @Param("example") TCustmorCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    int updateByExample(@Param("record") TCustmorCredit record, @Param("example") TCustmorCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    int updateByPrimaryKeySelective(TCustmorCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CUSTMOR_CREDIT
     *
     * @mbg.generated Wed Oct 25 16:07:52 CST 2017
     */
    int updateByPrimaryKey(TCustmorCredit record);
}