package com.byj.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TExpenseDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public TExpenseDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andExpenseNoIsNull() {
            addCriterion("EXPENSE_NO is null");
            return (Criteria) this;
        }

        public Criteria andExpenseNoIsNotNull() {
            addCriterion("EXPENSE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andExpenseNoEqualTo(String value) {
            addCriterion("EXPENSE_NO =", value, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoNotEqualTo(String value) {
            addCriterion("EXPENSE_NO <>", value, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoGreaterThan(String value) {
            addCriterion("EXPENSE_NO >", value, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoGreaterThanOrEqualTo(String value) {
            addCriterion("EXPENSE_NO >=", value, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoLessThan(String value) {
            addCriterion("EXPENSE_NO <", value, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoLessThanOrEqualTo(String value) {
            addCriterion("EXPENSE_NO <=", value, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoLike(String value) {
            addCriterion("EXPENSE_NO like", value, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoNotLike(String value) {
            addCriterion("EXPENSE_NO not like", value, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoIn(List<String> values) {
            addCriterion("EXPENSE_NO in", values, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoNotIn(List<String> values) {
            addCriterion("EXPENSE_NO not in", values, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoBetween(String value1, String value2) {
            addCriterion("EXPENSE_NO between", value1, value2, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseNoNotBetween(String value1, String value2) {
            addCriterion("EXPENSE_NO not between", value1, value2, "expenseNo");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeIsNull() {
            addCriterion("EXPENSE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeIsNotNull() {
            addCriterion("EXPENSE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeEqualTo(String value) {
            addCriterion("EXPENSE_TYPE =", value, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeNotEqualTo(String value) {
            addCriterion("EXPENSE_TYPE <>", value, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeGreaterThan(String value) {
            addCriterion("EXPENSE_TYPE >", value, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("EXPENSE_TYPE >=", value, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeLessThan(String value) {
            addCriterion("EXPENSE_TYPE <", value, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeLessThanOrEqualTo(String value) {
            addCriterion("EXPENSE_TYPE <=", value, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeLike(String value) {
            addCriterion("EXPENSE_TYPE like", value, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeNotLike(String value) {
            addCriterion("EXPENSE_TYPE not like", value, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeIn(List<String> values) {
            addCriterion("EXPENSE_TYPE in", values, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeNotIn(List<String> values) {
            addCriterion("EXPENSE_TYPE not in", values, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeBetween(String value1, String value2) {
            addCriterion("EXPENSE_TYPE between", value1, value2, "expenseType");
            return (Criteria) this;
        }

        public Criteria andExpenseTypeNotBetween(String value1, String value2) {
            addCriterion("EXPENSE_TYPE not between", value1, value2, "expenseType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeIsNull() {
            addCriterion("ELECTRIC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andElectricTypeIsNotNull() {
            addCriterion("ELECTRIC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andElectricTypeEqualTo(String value) {
            addCriterion("ELECTRIC_TYPE =", value, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeNotEqualTo(String value) {
            addCriterion("ELECTRIC_TYPE <>", value, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeGreaterThan(String value) {
            addCriterion("ELECTRIC_TYPE >", value, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ELECTRIC_TYPE >=", value, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeLessThan(String value) {
            addCriterion("ELECTRIC_TYPE <", value, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeLessThanOrEqualTo(String value) {
            addCriterion("ELECTRIC_TYPE <=", value, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeLike(String value) {
            addCriterion("ELECTRIC_TYPE like", value, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeNotLike(String value) {
            addCriterion("ELECTRIC_TYPE not like", value, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeIn(List<String> values) {
            addCriterion("ELECTRIC_TYPE in", values, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeNotIn(List<String> values) {
            addCriterion("ELECTRIC_TYPE not in", values, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeBetween(String value1, String value2) {
            addCriterion("ELECTRIC_TYPE between", value1, value2, "electricType");
            return (Criteria) this;
        }

        public Criteria andElectricTypeNotBetween(String value1, String value2) {
            addCriterion("ELECTRIC_TYPE not between", value1, value2, "electricType");
            return (Criteria) this;
        }

        public Criteria andToolNoIsNull() {
            addCriterion("TOOL_NO is null");
            return (Criteria) this;
        }

        public Criteria andToolNoIsNotNull() {
            addCriterion("TOOL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andToolNoEqualTo(String value) {
            addCriterion("TOOL_NO =", value, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoNotEqualTo(String value) {
            addCriterion("TOOL_NO <>", value, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoGreaterThan(String value) {
            addCriterion("TOOL_NO >", value, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoGreaterThanOrEqualTo(String value) {
            addCriterion("TOOL_NO >=", value, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoLessThan(String value) {
            addCriterion("TOOL_NO <", value, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoLessThanOrEqualTo(String value) {
            addCriterion("TOOL_NO <=", value, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoLike(String value) {
            addCriterion("TOOL_NO like", value, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoNotLike(String value) {
            addCriterion("TOOL_NO not like", value, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoIn(List<String> values) {
            addCriterion("TOOL_NO in", values, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoNotIn(List<String> values) {
            addCriterion("TOOL_NO not in", values, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoBetween(String value1, String value2) {
            addCriterion("TOOL_NO between", value1, value2, "toolNo");
            return (Criteria) this;
        }

        public Criteria andToolNoNotBetween(String value1, String value2) {
            addCriterion("TOOL_NO not between", value1, value2, "toolNo");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("QUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("QUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(BigDecimal value) {
            addCriterion("QUANTITY =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(BigDecimal value) {
            addCriterion("QUANTITY <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(BigDecimal value) {
            addCriterion("QUANTITY >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("QUANTITY >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(BigDecimal value) {
            addCriterion("QUANTITY <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("QUANTITY <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<BigDecimal> values) {
            addCriterion("QUANTITY in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<BigDecimal> values) {
            addCriterion("QUANTITY not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUANTITY between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUANTITY not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNull() {
            addCriterion("UNIT_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIsNotNull() {
            addCriterion("UNIT_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andUnitPriceEqualTo(BigDecimal value) {
            addCriterion("UNIT_PRICE =", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotEqualTo(BigDecimal value) {
            addCriterion("UNIT_PRICE <>", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThan(BigDecimal value) {
            addCriterion("UNIT_PRICE >", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UNIT_PRICE >=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThan(BigDecimal value) {
            addCriterion("UNIT_PRICE <", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UNIT_PRICE <=", value, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceIn(List<BigDecimal> values) {
            addCriterion("UNIT_PRICE in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotIn(List<BigDecimal> values) {
            addCriterion("UNIT_PRICE not in", values, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNIT_PRICE between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andUnitPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNIT_PRICE not between", value1, value2, "unitPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("TOTAL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("TOTAL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("TOTAL_PRICE >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(BigDecimal value) {
            addCriterion("TOTAL_PRICE <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_PRICE <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<BigDecimal> values) {
            addCriterion("TOTAL_PRICE in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("TOTAL_PRICE not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_PRICE between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_PRICE not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andExpenseDateIsNull() {
            addCriterion("EXPENSE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpenseDateIsNotNull() {
            addCriterion("EXPENSE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpenseDateEqualTo(Date value) {
            addCriterionForJDBCDate("EXPENSE_DATE =", value, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("EXPENSE_DATE <>", value, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateGreaterThan(Date value) {
            addCriterionForJDBCDate("EXPENSE_DATE >", value, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPENSE_DATE >=", value, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateLessThan(Date value) {
            addCriterionForJDBCDate("EXPENSE_DATE <", value, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPENSE_DATE <=", value, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateIn(List<Date> values) {
            addCriterionForJDBCDate("EXPENSE_DATE in", values, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("EXPENSE_DATE not in", values, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPENSE_DATE between", value1, value2, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andExpenseDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPENSE_DATE not between", value1, value2, "expenseDate");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("IS_VALID is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("IS_VALID is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(String value) {
            addCriterion("IS_VALID =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(String value) {
            addCriterion("IS_VALID <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(String value) {
            addCriterion("IS_VALID >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(String value) {
            addCriterion("IS_VALID >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(String value) {
            addCriterion("IS_VALID <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(String value) {
            addCriterion("IS_VALID <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLike(String value) {
            addCriterion("IS_VALID like", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotLike(String value) {
            addCriterion("IS_VALID not like", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<String> values) {
            addCriterion("IS_VALID in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<String> values) {
            addCriterion("IS_VALID not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(String value1, String value2) {
            addCriterion("IS_VALID between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(String value1, String value2) {
            addCriterion("IS_VALID not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andApplyOprIsNull() {
            addCriterion("APPLY_OPR is null");
            return (Criteria) this;
        }

        public Criteria andApplyOprIsNotNull() {
            addCriterion("APPLY_OPR is not null");
            return (Criteria) this;
        }

        public Criteria andApplyOprEqualTo(String value) {
            addCriterion("APPLY_OPR =", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprNotEqualTo(String value) {
            addCriterion("APPLY_OPR <>", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprGreaterThan(String value) {
            addCriterion("APPLY_OPR >", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_OPR >=", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprLessThan(String value) {
            addCriterion("APPLY_OPR <", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprLessThanOrEqualTo(String value) {
            addCriterion("APPLY_OPR <=", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprLike(String value) {
            addCriterion("APPLY_OPR like", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprNotLike(String value) {
            addCriterion("APPLY_OPR not like", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprIn(List<String> values) {
            addCriterion("APPLY_OPR in", values, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprNotIn(List<String> values) {
            addCriterion("APPLY_OPR not in", values, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprBetween(String value1, String value2) {
            addCriterion("APPLY_OPR between", value1, value2, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprNotBetween(String value1, String value2) {
            addCriterion("APPLY_OPR not between", value1, value2, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNull() {
            addCriterion("APPLY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNotNull() {
            addCriterion("APPLY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDateEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_DATE =", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_DATE <>", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThan(Date value) {
            addCriterionForJDBCDate("APPLY_DATE >", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_DATE >=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThan(Date value) {
            addCriterionForJDBCDate("APPLY_DATE <", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_DATE <=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateIn(List<Date> values) {
            addCriterionForJDBCDate("APPLY_DATE in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("APPLY_DATE not in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("APPLY_DATE between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("APPLY_DATE not between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalIsNull() {
            addCriterion("AMMETER_TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalIsNotNull() {
            addCriterion("AMMETER_TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalEqualTo(BigDecimal value) {
            addCriterion("AMMETER_TOTAL =", value, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalNotEqualTo(BigDecimal value) {
            addCriterion("AMMETER_TOTAL <>", value, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalGreaterThan(BigDecimal value) {
            addCriterion("AMMETER_TOTAL >", value, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMMETER_TOTAL >=", value, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalLessThan(BigDecimal value) {
            addCriterion("AMMETER_TOTAL <", value, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMMETER_TOTAL <=", value, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalIn(List<BigDecimal> values) {
            addCriterion("AMMETER_TOTAL in", values, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalNotIn(List<BigDecimal> values) {
            addCriterion("AMMETER_TOTAL not in", values, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMMETER_TOTAL between", value1, value2, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMMETER_TOTAL not between", value1, value2, "ammeterTotal");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbIsNull() {
            addCriterion("AMMETER_HB is null");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbIsNotNull() {
            addCriterion("AMMETER_HB is not null");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbEqualTo(BigDecimal value) {
            addCriterion("AMMETER_HB =", value, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbNotEqualTo(BigDecimal value) {
            addCriterion("AMMETER_HB <>", value, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbGreaterThan(BigDecimal value) {
            addCriterion("AMMETER_HB >", value, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMMETER_HB >=", value, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbLessThan(BigDecimal value) {
            addCriterion("AMMETER_HB <", value, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMMETER_HB <=", value, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbIn(List<BigDecimal> values) {
            addCriterion("AMMETER_HB in", values, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbNotIn(List<BigDecimal> values) {
            addCriterion("AMMETER_HB not in", values, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMMETER_HB between", value1, value2, "ammeterHb");
            return (Criteria) this;
        }

        public Criteria andAmmeterHbNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMMETER_HB not between", value1, value2, "ammeterHb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated do_not_delete_during_merge Tue May 15 21:38:24 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}