package com.byj.dao;

import com.byj.dao.TExpenseDetail;
import com.byj.dao.TExpenseDetailExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TExpenseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    long countByExample(TExpenseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int deleteByExample(TExpenseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int insert(TExpenseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int insertSelective(TExpenseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    List<TExpenseDetail> selectByExampleWithRowbounds(TExpenseDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    List<TExpenseDetail> selectByExample(TExpenseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    TExpenseDetail selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TExpenseDetail record, @Param("example") TExpenseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByExample(@Param("record") TExpenseDetail record, @Param("example") TExpenseDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByPrimaryKeySelective(TExpenseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXPENSE_DETAIL
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByPrimaryKey(TExpenseDetail record);

    TExpenseDetail sumByTool(String toolNo);
}