package com.byj.dao;

import com.byj.dao.TProjectTflow;
import com.byj.dao.TProjectTflowExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TProjectTflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    long countByExample(TProjectTflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int deleteByExample(TProjectTflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int insert(TProjectTflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int insertSelective(TProjectTflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    List<TProjectTflow> selectByExampleWithRowbounds(TProjectTflowExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    List<TProjectTflow> selectByExample(TProjectTflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    TProjectTflow selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TProjectTflow record, @Param("example") TProjectTflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByExample(@Param("record") TProjectTflow record, @Param("example") TProjectTflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByPrimaryKeySelective(TProjectTflow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_TFLOW
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByPrimaryKey(TProjectTflow record);
}