package com.byj.dao;

import com.byj.dao.TProjectBase;
import com.byj.dao.TProjectBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TProjectBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    long countByExample(TProjectBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    int deleteByExample(TProjectBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    int deleteByPrimaryKey(String projectNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    int insert(TProjectBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    int insertSelective(TProjectBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    List<TProjectBase> selectByExampleWithRowbounds(TProjectBaseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    List<TProjectBase> selectByExample(TProjectBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    TProjectBase selectByPrimaryKey(String projectNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") TProjectBase record, @Param("example") TProjectBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    int updateByExample(@Param("record") TProjectBase record, @Param("example") TProjectBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    int updateByPrimaryKeySelective(TProjectBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    int updateByPrimaryKey(TProjectBase record);

    TProjectBase countHisByCustomer(String customerNo);
}