package com.byj.dao;

import java.math.BigDecimal;
import java.util.Date;

public class TProjectBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.PROJECT_NO
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private String projectNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.PROJECT_NAME
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.CUSTOMER_NO
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private String customerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.BEGIN_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private Date beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.END_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private BigDecimal quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.TOTAL_PRICE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.END_QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private BigDecimal endQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.PICKUP_QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private BigDecimal pickupQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.PROCEEDS_STATUS
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private String proceedsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.ACT_AMT
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private BigDecimal actAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.IS_VALID
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.STATUS
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.APPLY_OPR
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private String applyOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.APPLY_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PROJECT_BASE.REMARK
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    private String remark;

    private int hisCount;

    private BigDecimal hisAmt;

    public int getHisCount() {
        return hisCount;
    }

    public void setHisCount(int hisCount) {
        this.hisCount = hisCount;
    }

    public BigDecimal getHisAmt() {
        return hisAmt;
    }

    public void setHisAmt(BigDecimal hisAmt) {
        this.hisAmt = hisAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.PROJECT_NO
     *
     * @return the value of T_PROJECT_BASE.PROJECT_NO
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.PROJECT_NO
     *
     * @param projectNo the value for T_PROJECT_BASE.PROJECT_NO
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.PROJECT_NAME
     *
     * @return the value of T_PROJECT_BASE.PROJECT_NAME
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.PROJECT_NAME
     *
     * @param projectName the value for T_PROJECT_BASE.PROJECT_NAME
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.CUSTOMER_NO
     *
     * @return the value of T_PROJECT_BASE.CUSTOMER_NO
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.CUSTOMER_NO
     *
     * @param customerNo the value for T_PROJECT_BASE.CUSTOMER_NO
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo == null ? null : customerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.BEGIN_DATE
     *
     * @return the value of T_PROJECT_BASE.BEGIN_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.BEGIN_DATE
     *
     * @param beginDate the value for T_PROJECT_BASE.BEGIN_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.END_DATE
     *
     * @return the value of T_PROJECT_BASE.END_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.END_DATE
     *
     * @param endDate the value for T_PROJECT_BASE.END_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.QUANTITY
     *
     * @return the value of T_PROJECT_BASE.QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.QUANTITY
     *
     * @param quantity the value for T_PROJECT_BASE.QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.TOTAL_PRICE
     *
     * @return the value of T_PROJECT_BASE.TOTAL_PRICE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.TOTAL_PRICE
     *
     * @param totalPrice the value for T_PROJECT_BASE.TOTAL_PRICE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.END_QUANTITY
     *
     * @return the value of T_PROJECT_BASE.END_QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public BigDecimal getEndQuantity() {
        return endQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.END_QUANTITY
     *
     * @param endQuantity the value for T_PROJECT_BASE.END_QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setEndQuantity(BigDecimal endQuantity) {
        this.endQuantity = endQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.PICKUP_QUANTITY
     *
     * @return the value of T_PROJECT_BASE.PICKUP_QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public BigDecimal getPickupQuantity() {
        return pickupQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.PICKUP_QUANTITY
     *
     * @param pickupQuantity the value for T_PROJECT_BASE.PICKUP_QUANTITY
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setPickupQuantity(BigDecimal pickupQuantity) {
        this.pickupQuantity = pickupQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.PROCEEDS_STATUS
     *
     * @return the value of T_PROJECT_BASE.PROCEEDS_STATUS
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public String getProceedsStatus() {
        return proceedsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.PROCEEDS_STATUS
     *
     * @param proceedsStatus the value for T_PROJECT_BASE.PROCEEDS_STATUS
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setProceedsStatus(String proceedsStatus) {
        this.proceedsStatus = proceedsStatus == null ? null : proceedsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.ACT_AMT
     *
     * @return the value of T_PROJECT_BASE.ACT_AMT
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public BigDecimal getActAmt() {
        return actAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.ACT_AMT
     *
     * @param actAmt the value for T_PROJECT_BASE.ACT_AMT
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setActAmt(BigDecimal actAmt) {
        this.actAmt = actAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.IS_VALID
     *
     * @return the value of T_PROJECT_BASE.IS_VALID
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.IS_VALID
     *
     * @param isValid the value for T_PROJECT_BASE.IS_VALID
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.STATUS
     *
     * @return the value of T_PROJECT_BASE.STATUS
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.STATUS
     *
     * @param status the value for T_PROJECT_BASE.STATUS
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.APPLY_OPR
     *
     * @return the value of T_PROJECT_BASE.APPLY_OPR
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public String getApplyOpr() {
        return applyOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.APPLY_OPR
     *
     * @param applyOpr the value for T_PROJECT_BASE.APPLY_OPR
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setApplyOpr(String applyOpr) {
        this.applyOpr = applyOpr == null ? null : applyOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.APPLY_DATE
     *
     * @return the value of T_PROJECT_BASE.APPLY_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.APPLY_DATE
     *
     * @param applyDate the value for T_PROJECT_BASE.APPLY_DATE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PROJECT_BASE.REMARK
     *
     * @return the value of T_PROJECT_BASE.REMARK
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PROJECT_BASE.REMARK
     *
     * @param remark the value for T_PROJECT_BASE.REMARK
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectNo=").append(projectNo);
        sb.append(", projectName=").append(projectName);
        sb.append(", customerNo=").append(customerNo);
        sb.append(", beginDate=").append(beginDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", quantity=").append(quantity);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", endQuantity=").append(endQuantity);
        sb.append(", pickupQuantity=").append(pickupQuantity);
        sb.append(", proceedsStatus=").append(proceedsStatus);
        sb.append(", actAmt=").append(actAmt);
        sb.append(", isValid=").append(isValid);
        sb.append(", status=").append(status);
        sb.append(", applyOpr=").append(applyOpr);
        sb.append(", applyDate=").append(applyDate);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TProjectBase other = (TProjectBase) that;
        return (this.getProjectNo() == null ? other.getProjectNo() == null : this.getProjectNo().equals(other.getProjectNo()))
            && (this.getProjectName() == null ? other.getProjectName() == null : this.getProjectName().equals(other.getProjectName()))
            && (this.getCustomerNo() == null ? other.getCustomerNo() == null : this.getCustomerNo().equals(other.getCustomerNo()))
            && (this.getBeginDate() == null ? other.getBeginDate() == null : this.getBeginDate().equals(other.getBeginDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getTotalPrice() == null ? other.getTotalPrice() == null : this.getTotalPrice().equals(other.getTotalPrice()))
            && (this.getEndQuantity() == null ? other.getEndQuantity() == null : this.getEndQuantity().equals(other.getEndQuantity()))
            && (this.getPickupQuantity() == null ? other.getPickupQuantity() == null : this.getPickupQuantity().equals(other.getPickupQuantity()))
            && (this.getProceedsStatus() == null ? other.getProceedsStatus() == null : this.getProceedsStatus().equals(other.getProceedsStatus()))
            && (this.getActAmt() == null ? other.getActAmt() == null : this.getActAmt().equals(other.getActAmt()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getApplyOpr() == null ? other.getApplyOpr() == null : this.getApplyOpr().equals(other.getApplyOpr()))
            && (this.getApplyDate() == null ? other.getApplyDate() == null : this.getApplyDate().equals(other.getApplyDate()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PROJECT_BASE
     *
     * @mbg.generated Wed May 16 21:15:21 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProjectNo() == null) ? 0 : getProjectNo().hashCode());
        result = prime * result + ((getProjectName() == null) ? 0 : getProjectName().hashCode());
        result = prime * result + ((getCustomerNo() == null) ? 0 : getCustomerNo().hashCode());
        result = prime * result + ((getBeginDate() == null) ? 0 : getBeginDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getTotalPrice() == null) ? 0 : getTotalPrice().hashCode());
        result = prime * result + ((getEndQuantity() == null) ? 0 : getEndQuantity().hashCode());
        result = prime * result + ((getPickupQuantity() == null) ? 0 : getPickupQuantity().hashCode());
        result = prime * result + ((getProceedsStatus() == null) ? 0 : getProceedsStatus().hashCode());
        result = prime * result + ((getActAmt() == null) ? 0 : getActAmt().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getApplyOpr() == null) ? 0 : getApplyOpr().hashCode());
        result = prime * result + ((getApplyDate() == null) ? 0 : getApplyDate().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}