package com.byj.dao;

import com.byj.dao.TSalary;
import com.byj.dao.TSalaryExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    long countByExample(TSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int deleteByExample(TSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int insert(TSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int insertSelective(TSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    List<TSalary> selectByExampleWithRowbounds(TSalaryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    List<TSalary> selectByExample(TSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    TSalary selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSalary record, @Param("example") TSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByExample(@Param("record") TSalary record, @Param("example") TSalaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByPrimaryKeySelective(TSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    int updateByPrimaryKey(TSalary record);
}