package com.byj.dao;

import java.math.BigDecimal;
import java.util.Date;

public class TSalary {
    private String strDate;

    public String getStrDate() {
        return strDate;
    }

    public void setStrDate(String strDate) {
        this.strDate = strDate;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.ID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.USER_ID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.MAN_HOUR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private BigDecimal manHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.UNIT_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private BigDecimal unitSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.ACT_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private BigDecimal actSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.IS_VALID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.STATUS
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.SALARY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private Date salaryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.APPLY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String applyOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.APPLY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.PAY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String payOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.PAY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.APPLY_REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String applyRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SALARY.PAY_REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String payRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.ID
     *
     * @return the value of T_SALARY.ID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.ID
     *
     * @param id the value for T_SALARY.ID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.USER_ID
     *
     * @return the value of T_SALARY.USER_ID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.USER_ID
     *
     * @param userId the value for T_SALARY.USER_ID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.MAN_HOUR
     *
     * @return the value of T_SALARY.MAN_HOUR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public BigDecimal getManHour() {
        return manHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.MAN_HOUR
     *
     * @param manHour the value for T_SALARY.MAN_HOUR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setManHour(BigDecimal manHour) {
        this.manHour = manHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.UNIT_SALARY
     *
     * @return the value of T_SALARY.UNIT_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public BigDecimal getUnitSalary() {
        return unitSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.UNIT_SALARY
     *
     * @param unitSalary the value for T_SALARY.UNIT_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setUnitSalary(BigDecimal unitSalary) {
        this.unitSalary = unitSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.SALARY
     *
     * @return the value of T_SALARY.SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.SALARY
     *
     * @param salary the value for T_SALARY.SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.ACT_SALARY
     *
     * @return the value of T_SALARY.ACT_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public BigDecimal getActSalary() {
        return actSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.ACT_SALARY
     *
     * @param actSalary the value for T_SALARY.ACT_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setActSalary(BigDecimal actSalary) {
        this.actSalary = actSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.IS_VALID
     *
     * @return the value of T_SALARY.IS_VALID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.IS_VALID
     *
     * @param isValid the value for T_SALARY.IS_VALID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.STATUS
     *
     * @return the value of T_SALARY.STATUS
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.STATUS
     *
     * @param status the value for T_SALARY.STATUS
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.SALARY_DATE
     *
     * @return the value of T_SALARY.SALARY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public Date getSalaryDate() {
        return salaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.SALARY_DATE
     *
     * @param salaryDate the value for T_SALARY.SALARY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setSalaryDate(Date salaryDate) {
        this.salaryDate = salaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.APPLY_OPR
     *
     * @return the value of T_SALARY.APPLY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getApplyOpr() {
        return applyOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.APPLY_OPR
     *
     * @param applyOpr the value for T_SALARY.APPLY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setApplyOpr(String applyOpr) {
        this.applyOpr = applyOpr == null ? null : applyOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.APPLY_DATE
     *
     * @return the value of T_SALARY.APPLY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.APPLY_DATE
     *
     * @param applyDate the value for T_SALARY.APPLY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.PAY_OPR
     *
     * @return the value of T_SALARY.PAY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getPayOpr() {
        return payOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.PAY_OPR
     *
     * @param payOpr the value for T_SALARY.PAY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setPayOpr(String payOpr) {
        this.payOpr = payOpr == null ? null : payOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.PAY_DATE
     *
     * @return the value of T_SALARY.PAY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.PAY_DATE
     *
     * @param payDate the value for T_SALARY.PAY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.APPLY_REMARK
     *
     * @return the value of T_SALARY.APPLY_REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getApplyRemark() {
        return applyRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.APPLY_REMARK
     *
     * @param applyRemark the value for T_SALARY.APPLY_REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setApplyRemark(String applyRemark) {
        this.applyRemark = applyRemark == null ? null : applyRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SALARY.PAY_REMARK
     *
     * @return the value of T_SALARY.PAY_REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getPayRemark() {
        return payRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SALARY.PAY_REMARK
     *
     * @param payRemark the value for T_SALARY.PAY_REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setPayRemark(String payRemark) {
        this.payRemark = payRemark == null ? null : payRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", manHour=").append(manHour);
        sb.append(", unitSalary=").append(unitSalary);
        sb.append(", salary=").append(salary);
        sb.append(", actSalary=").append(actSalary);
        sb.append(", isValid=").append(isValid);
        sb.append(", status=").append(status);
        sb.append(", salaryDate=").append(salaryDate);
        sb.append(", applyOpr=").append(applyOpr);
        sb.append(", applyDate=").append(applyDate);
        sb.append(", payOpr=").append(payOpr);
        sb.append(", payDate=").append(payDate);
        sb.append(", applyRemark=").append(applyRemark);
        sb.append(", payRemark=").append(payRemark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TSalary other = (TSalary) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getManHour() == null ? other.getManHour() == null : this.getManHour().equals(other.getManHour()))
            && (this.getUnitSalary() == null ? other.getUnitSalary() == null : this.getUnitSalary().equals(other.getUnitSalary()))
            && (this.getSalary() == null ? other.getSalary() == null : this.getSalary().equals(other.getSalary()))
            && (this.getActSalary() == null ? other.getActSalary() == null : this.getActSalary().equals(other.getActSalary()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getSalaryDate() == null ? other.getSalaryDate() == null : this.getSalaryDate().equals(other.getSalaryDate()))
            && (this.getApplyOpr() == null ? other.getApplyOpr() == null : this.getApplyOpr().equals(other.getApplyOpr()))
            && (this.getApplyDate() == null ? other.getApplyDate() == null : this.getApplyDate().equals(other.getApplyDate()))
            && (this.getPayOpr() == null ? other.getPayOpr() == null : this.getPayOpr().equals(other.getPayOpr()))
            && (this.getPayDate() == null ? other.getPayDate() == null : this.getPayDate().equals(other.getPayDate()))
            && (this.getApplyRemark() == null ? other.getApplyRemark() == null : this.getApplyRemark().equals(other.getApplyRemark()))
            && (this.getPayRemark() == null ? other.getPayRemark() == null : this.getPayRemark().equals(other.getPayRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getManHour() == null) ? 0 : getManHour().hashCode());
        result = prime * result + ((getUnitSalary() == null) ? 0 : getUnitSalary().hashCode());
        result = prime * result + ((getSalary() == null) ? 0 : getSalary().hashCode());
        result = prime * result + ((getActSalary() == null) ? 0 : getActSalary().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getSalaryDate() == null) ? 0 : getSalaryDate().hashCode());
        result = prime * result + ((getApplyOpr() == null) ? 0 : getApplyOpr().hashCode());
        result = prime * result + ((getApplyDate() == null) ? 0 : getApplyDate().hashCode());
        result = prime * result + ((getPayOpr() == null) ? 0 : getPayOpr().hashCode());
        result = prime * result + ((getPayDate() == null) ? 0 : getPayDate().hashCode());
        result = prime * result + ((getApplyRemark() == null) ? 0 : getApplyRemark().hashCode());
        result = prime * result + ((getPayRemark() == null) ? 0 : getPayRemark().hashCode());
        return result;
    }
}