package com.byj.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TSalaryExample {
    protected Integer limitStart;

    protected Integer limitEnd;

    public Integer getLimitStart() {
        return limitStart;
    }

    public void setLimitStart(Integer limitStart) {
        this.limitStart = limitStart;
    }

    public Integer getLimitEnd() {
        return limitEnd;
    }

    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd = limitEnd;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public TSalaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andManHourIsNull() {
            addCriterion("MAN_HOUR is null");
            return (Criteria) this;
        }

        public Criteria andManHourIsNotNull() {
            addCriterion("MAN_HOUR is not null");
            return (Criteria) this;
        }

        public Criteria andManHourEqualTo(BigDecimal value) {
            addCriterion("MAN_HOUR =", value, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourNotEqualTo(BigDecimal value) {
            addCriterion("MAN_HOUR <>", value, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourGreaterThan(BigDecimal value) {
            addCriterion("MAN_HOUR >", value, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MAN_HOUR >=", value, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourLessThan(BigDecimal value) {
            addCriterion("MAN_HOUR <", value, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MAN_HOUR <=", value, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourIn(List<BigDecimal> values) {
            addCriterion("MAN_HOUR in", values, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourNotIn(List<BigDecimal> values) {
            addCriterion("MAN_HOUR not in", values, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MAN_HOUR between", value1, value2, "manHour");
            return (Criteria) this;
        }

        public Criteria andManHourNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MAN_HOUR not between", value1, value2, "manHour");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryIsNull() {
            addCriterion("UNIT_SALARY is null");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryIsNotNull() {
            addCriterion("UNIT_SALARY is not null");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryEqualTo(BigDecimal value) {
            addCriterion("UNIT_SALARY =", value, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryNotEqualTo(BigDecimal value) {
            addCriterion("UNIT_SALARY <>", value, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryGreaterThan(BigDecimal value) {
            addCriterion("UNIT_SALARY >", value, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UNIT_SALARY >=", value, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryLessThan(BigDecimal value) {
            addCriterion("UNIT_SALARY <", value, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UNIT_SALARY <=", value, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryIn(List<BigDecimal> values) {
            addCriterion("UNIT_SALARY in", values, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryNotIn(List<BigDecimal> values) {
            addCriterion("UNIT_SALARY not in", values, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNIT_SALARY between", value1, value2, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andUnitSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UNIT_SALARY not between", value1, value2, "unitSalary");
            return (Criteria) this;
        }

        public Criteria andSalaryIsNull() {
            addCriterion("SALARY is null");
            return (Criteria) this;
        }

        public Criteria andSalaryIsNotNull() {
            addCriterion("SALARY is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryEqualTo(BigDecimal value) {
            addCriterion("SALARY =", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotEqualTo(BigDecimal value) {
            addCriterion("SALARY <>", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryGreaterThan(BigDecimal value) {
            addCriterion("SALARY >", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SALARY >=", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLessThan(BigDecimal value) {
            addCriterion("SALARY <", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SALARY <=", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryIn(List<BigDecimal> values) {
            addCriterion("SALARY in", values, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotIn(List<BigDecimal> values) {
            addCriterion("SALARY not in", values, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SALARY between", value1, value2, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SALARY not between", value1, value2, "salary");
            return (Criteria) this;
        }

        public Criteria andActSalaryIsNull() {
            addCriterion("ACT_SALARY is null");
            return (Criteria) this;
        }

        public Criteria andActSalaryIsNotNull() {
            addCriterion("ACT_SALARY is not null");
            return (Criteria) this;
        }

        public Criteria andActSalaryEqualTo(BigDecimal value) {
            addCriterion("ACT_SALARY =", value, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryNotEqualTo(BigDecimal value) {
            addCriterion("ACT_SALARY <>", value, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryGreaterThan(BigDecimal value) {
            addCriterion("ACT_SALARY >", value, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_SALARY >=", value, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryLessThan(BigDecimal value) {
            addCriterion("ACT_SALARY <", value, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACT_SALARY <=", value, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryIn(List<BigDecimal> values) {
            addCriterion("ACT_SALARY in", values, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryNotIn(List<BigDecimal> values) {
            addCriterion("ACT_SALARY not in", values, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_SALARY between", value1, value2, "actSalary");
            return (Criteria) this;
        }

        public Criteria andActSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACT_SALARY not between", value1, value2, "actSalary");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("IS_VALID is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("IS_VALID is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(String value) {
            addCriterion("IS_VALID =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(String value) {
            addCriterion("IS_VALID <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(String value) {
            addCriterion("IS_VALID >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(String value) {
            addCriterion("IS_VALID >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(String value) {
            addCriterion("IS_VALID <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(String value) {
            addCriterion("IS_VALID <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLike(String value) {
            addCriterion("IS_VALID like", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotLike(String value) {
            addCriterion("IS_VALID not like", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<String> values) {
            addCriterion("IS_VALID in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<String> values) {
            addCriterion("IS_VALID not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(String value1, String value2) {
            addCriterion("IS_VALID between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(String value1, String value2) {
            addCriterion("IS_VALID not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSalaryDateIsNull() {
            addCriterion("SALARY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSalaryDateIsNotNull() {
            addCriterion("SALARY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryDateEqualTo(Date value) {
            addCriterionForJDBCDate("SALARY_DATE =", value, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("SALARY_DATE <>", value, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateGreaterThan(Date value) {
            addCriterionForJDBCDate("SALARY_DATE >", value, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SALARY_DATE >=", value, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateLessThan(Date value) {
            addCriterionForJDBCDate("SALARY_DATE <", value, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SALARY_DATE <=", value, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateIn(List<Date> values) {
            addCriterionForJDBCDate("SALARY_DATE in", values, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("SALARY_DATE not in", values, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SALARY_DATE between", value1, value2, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andSalaryDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SALARY_DATE not between", value1, value2, "salaryDate");
            return (Criteria) this;
        }

        public Criteria andApplyOprIsNull() {
            addCriterion("APPLY_OPR is null");
            return (Criteria) this;
        }

        public Criteria andApplyOprIsNotNull() {
            addCriterion("APPLY_OPR is not null");
            return (Criteria) this;
        }

        public Criteria andApplyOprEqualTo(String value) {
            addCriterion("APPLY_OPR =", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprNotEqualTo(String value) {
            addCriterion("APPLY_OPR <>", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprGreaterThan(String value) {
            addCriterion("APPLY_OPR >", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_OPR >=", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprLessThan(String value) {
            addCriterion("APPLY_OPR <", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprLessThanOrEqualTo(String value) {
            addCriterion("APPLY_OPR <=", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprLike(String value) {
            addCriterion("APPLY_OPR like", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprNotLike(String value) {
            addCriterion("APPLY_OPR not like", value, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprIn(List<String> values) {
            addCriterion("APPLY_OPR in", values, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprNotIn(List<String> values) {
            addCriterion("APPLY_OPR not in", values, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprBetween(String value1, String value2) {
            addCriterion("APPLY_OPR between", value1, value2, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyOprNotBetween(String value1, String value2) {
            addCriterion("APPLY_OPR not between", value1, value2, "applyOpr");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNull() {
            addCriterion("APPLY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNotNull() {
            addCriterion("APPLY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDateEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_DATE =", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_DATE <>", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThan(Date value) {
            addCriterionForJDBCDate("APPLY_DATE >", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_DATE >=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThan(Date value) {
            addCriterionForJDBCDate("APPLY_DATE <", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("APPLY_DATE <=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateIn(List<Date> values) {
            addCriterionForJDBCDate("APPLY_DATE in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("APPLY_DATE not in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("APPLY_DATE between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("APPLY_DATE not between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andPayOprIsNull() {
            addCriterion("PAY_OPR is null");
            return (Criteria) this;
        }

        public Criteria andPayOprIsNotNull() {
            addCriterion("PAY_OPR is not null");
            return (Criteria) this;
        }

        public Criteria andPayOprEqualTo(String value) {
            addCriterion("PAY_OPR =", value, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprNotEqualTo(String value) {
            addCriterion("PAY_OPR <>", value, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprGreaterThan(String value) {
            addCriterion("PAY_OPR >", value, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_OPR >=", value, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprLessThan(String value) {
            addCriterion("PAY_OPR <", value, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprLessThanOrEqualTo(String value) {
            addCriterion("PAY_OPR <=", value, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprLike(String value) {
            addCriterion("PAY_OPR like", value, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprNotLike(String value) {
            addCriterion("PAY_OPR not like", value, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprIn(List<String> values) {
            addCriterion("PAY_OPR in", values, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprNotIn(List<String> values) {
            addCriterion("PAY_OPR not in", values, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprBetween(String value1, String value2) {
            addCriterion("PAY_OPR between", value1, value2, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayOprNotBetween(String value1, String value2) {
            addCriterion("PAY_OPR not between", value1, value2, "payOpr");
            return (Criteria) this;
        }

        public Criteria andPayDateIsNull() {
            addCriterion("PAY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPayDateIsNotNull() {
            addCriterion("PAY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPayDateEqualTo(Date value) {
            addCriterionForJDBCDate("PAY_DATE =", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PAY_DATE <>", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateGreaterThan(Date value) {
            addCriterionForJDBCDate("PAY_DATE >", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PAY_DATE >=", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateLessThan(Date value) {
            addCriterionForJDBCDate("PAY_DATE <", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PAY_DATE <=", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateIn(List<Date> values) {
            addCriterionForJDBCDate("PAY_DATE in", values, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PAY_DATE not in", values, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PAY_DATE between", value1, value2, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PAY_DATE not between", value1, value2, "payDate");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkIsNull() {
            addCriterion("APPLY_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkIsNotNull() {
            addCriterion("APPLY_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkEqualTo(String value) {
            addCriterion("APPLY_REMARK =", value, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkNotEqualTo(String value) {
            addCriterion("APPLY_REMARK <>", value, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkGreaterThan(String value) {
            addCriterion("APPLY_REMARK >", value, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_REMARK >=", value, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkLessThan(String value) {
            addCriterion("APPLY_REMARK <", value, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkLessThanOrEqualTo(String value) {
            addCriterion("APPLY_REMARK <=", value, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkLike(String value) {
            addCriterion("APPLY_REMARK like", value, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkNotLike(String value) {
            addCriterion("APPLY_REMARK not like", value, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkIn(List<String> values) {
            addCriterion("APPLY_REMARK in", values, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkNotIn(List<String> values) {
            addCriterion("APPLY_REMARK not in", values, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkBetween(String value1, String value2) {
            addCriterion("APPLY_REMARK between", value1, value2, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andApplyRemarkNotBetween(String value1, String value2) {
            addCriterion("APPLY_REMARK not between", value1, value2, "applyRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkIsNull() {
            addCriterion("PAY_REMARK is null");
            return (Criteria) this;
        }

        public Criteria andPayRemarkIsNotNull() {
            addCriterion("PAY_REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andPayRemarkEqualTo(String value) {
            addCriterion("PAY_REMARK =", value, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkNotEqualTo(String value) {
            addCriterion("PAY_REMARK <>", value, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkGreaterThan(String value) {
            addCriterion("PAY_REMARK >", value, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_REMARK >=", value, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkLessThan(String value) {
            addCriterion("PAY_REMARK <", value, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkLessThanOrEqualTo(String value) {
            addCriterion("PAY_REMARK <=", value, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkLike(String value) {
            addCriterion("PAY_REMARK like", value, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkNotLike(String value) {
            addCriterion("PAY_REMARK not like", value, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkIn(List<String> values) {
            addCriterion("PAY_REMARK in", values, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkNotIn(List<String> values) {
            addCriterion("PAY_REMARK not in", values, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkBetween(String value1, String value2) {
            addCriterion("PAY_REMARK between", value1, value2, "payRemark");
            return (Criteria) this;
        }

        public Criteria andPayRemarkNotBetween(String value1, String value2) {
            addCriterion("PAY_REMARK not between", value1, value2, "payRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SALARY
     *
     * @mbg.generated do_not_delete_during_merge Tue May 15 21:38:24 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SALARY
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}