package com.byj.dao;

import java.util.Date;

public class TWorkpiece {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORKPIECE.WORKPIECE_NO
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String workpieceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORKPIECE.WORKPIECE_NAME
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String workpieceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORKPIECE.UNIT
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORKPIECE.IS_VALID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORKPIECE.STATUS
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORKPIECE.APPLY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String applyOpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORKPIECE.APPLY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_WORKPIECE.REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    private String remark;

    private int finishCount;
    private int totalCount;
    private int pickupCount;

    public int getPickupCount() {
        return pickupCount;
    }

    public void setPickupCount(int pickupCount) {
        this.pickupCount = pickupCount;
    }

    public int getFinishCount() {
        return finishCount;
    }

    public void setFinishCount(int finishCount) {
        this.finishCount = finishCount;
    }

    public int getTotalCount() {
        return totalCount;
    }

    public void setTotalCount(int totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORKPIECE.WORKPIECE_NO
     *
     * @return the value of T_WORKPIECE.WORKPIECE_NO
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getWorkpieceNo() {
        return workpieceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORKPIECE.WORKPIECE_NO
     *
     * @param workpieceNo the value for T_WORKPIECE.WORKPIECE_NO
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setWorkpieceNo(String workpieceNo) {
        this.workpieceNo = workpieceNo == null ? null : workpieceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORKPIECE.WORKPIECE_NAME
     *
     * @return the value of T_WORKPIECE.WORKPIECE_NAME
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getWorkpieceName() {
        return workpieceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORKPIECE.WORKPIECE_NAME
     *
     * @param workpieceName the value for T_WORKPIECE.WORKPIECE_NAME
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setWorkpieceName(String workpieceName) {
        this.workpieceName = workpieceName == null ? null : workpieceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORKPIECE.UNIT
     *
     * @return the value of T_WORKPIECE.UNIT
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORKPIECE.UNIT
     *
     * @param unit the value for T_WORKPIECE.UNIT
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORKPIECE.IS_VALID
     *
     * @return the value of T_WORKPIECE.IS_VALID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORKPIECE.IS_VALID
     *
     * @param isValid the value for T_WORKPIECE.IS_VALID
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORKPIECE.STATUS
     *
     * @return the value of T_WORKPIECE.STATUS
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORKPIECE.STATUS
     *
     * @param status the value for T_WORKPIECE.STATUS
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORKPIECE.APPLY_OPR
     *
     * @return the value of T_WORKPIECE.APPLY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getApplyOpr() {
        return applyOpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORKPIECE.APPLY_OPR
     *
     * @param applyOpr the value for T_WORKPIECE.APPLY_OPR
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setApplyOpr(String applyOpr) {
        this.applyOpr = applyOpr == null ? null : applyOpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORKPIECE.APPLY_DATE
     *
     * @return the value of T_WORKPIECE.APPLY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORKPIECE.APPLY_DATE
     *
     * @param applyDate the value for T_WORKPIECE.APPLY_DATE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_WORKPIECE.REMARK
     *
     * @return the value of T_WORKPIECE.REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_WORKPIECE.REMARK
     *
     * @param remark the value for T_WORKPIECE.REMARK
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_WORKPIECE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", workpieceNo=").append(workpieceNo);
        sb.append(", workpieceName=").append(workpieceName);
        sb.append(", unit=").append(unit);
        sb.append(", isValid=").append(isValid);
        sb.append(", status=").append(status);
        sb.append(", applyOpr=").append(applyOpr);
        sb.append(", applyDate=").append(applyDate);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_WORKPIECE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TWorkpiece other = (TWorkpiece) that;
        return (this.getWorkpieceNo() == null ? other.getWorkpieceNo() == null : this.getWorkpieceNo().equals(other.getWorkpieceNo()))
            && (this.getWorkpieceName() == null ? other.getWorkpieceName() == null : this.getWorkpieceName().equals(other.getWorkpieceName()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getApplyOpr() == null ? other.getApplyOpr() == null : this.getApplyOpr().equals(other.getApplyOpr()))
            && (this.getApplyDate() == null ? other.getApplyDate() == null : this.getApplyDate().equals(other.getApplyDate()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_WORKPIECE
     *
     * @mbg.generated Tue May 15 21:38:24 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWorkpieceNo() == null) ? 0 : getWorkpieceNo().hashCode());
        result = prime * result + ((getWorkpieceName() == null) ? 0 : getWorkpieceName().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getApplyOpr() == null) ? 0 : getApplyOpr().hashCode());
        result = prime * result + ((getApplyDate() == null) ? 0 : getApplyDate().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}