package bas.jeda.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class JedaUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public JedaUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNull() {
            addCriterion("POSITION_ID is null");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNotNull() {
            addCriterion("POSITION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPositionIdEqualTo(String value) {
            addCriterion("POSITION_ID =", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotEqualTo(String value) {
            addCriterion("POSITION_ID <>", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThan(String value) {
            addCriterion("POSITION_ID >", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThanOrEqualTo(String value) {
            addCriterion("POSITION_ID >=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThan(String value) {
            addCriterion("POSITION_ID <", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThanOrEqualTo(String value) {
            addCriterion("POSITION_ID <=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLike(String value) {
            addCriterion("POSITION_ID like", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotLike(String value) {
            addCriterion("POSITION_ID not like", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdIn(List<String> values) {
            addCriterion("POSITION_ID in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotIn(List<String> values) {
            addCriterion("POSITION_ID not in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdBetween(String value1, String value2) {
            addCriterion("POSITION_ID between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotBetween(String value1, String value2) {
            addCriterion("POSITION_ID not between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(String value) {
            addCriterion("ORG_ID =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(String value) {
            addCriterion("ORG_ID <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(String value) {
            addCriterion("ORG_ID >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_ID >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(String value) {
            addCriterion("ORG_ID <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(String value) {
            addCriterion("ORG_ID <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLike(String value) {
            addCriterion("ORG_ID like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotLike(String value) {
            addCriterion("ORG_ID not like", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<String> values) {
            addCriterion("ORG_ID in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<String> values) {
            addCriterion("ORG_ID not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(String value1, String value2) {
            addCriterion("ORG_ID between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(String value1, String value2) {
            addCriterion("ORG_ID not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("USER_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("USER_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("USER_PASSWORD =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("USER_PASSWORD <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("USER_PASSWORD >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("USER_PASSWORD >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("USER_PASSWORD <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("USER_PASSWORD <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("USER_PASSWORD like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("USER_PASSWORD not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("USER_PASSWORD in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("USER_PASSWORD not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("USER_PASSWORD between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("USER_PASSWORD not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserIdNoIsNull() {
            addCriterion("USER_ID_NO is null");
            return (Criteria) this;
        }

        public Criteria andUserIdNoIsNotNull() {
            addCriterion("USER_ID_NO is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdNoEqualTo(String value) {
            addCriterion("USER_ID_NO =", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoNotEqualTo(String value) {
            addCriterion("USER_ID_NO <>", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoGreaterThan(String value) {
            addCriterion("USER_ID_NO >", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID_NO >=", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoLessThan(String value) {
            addCriterion("USER_ID_NO <", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoLessThanOrEqualTo(String value) {
            addCriterion("USER_ID_NO <=", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoLike(String value) {
            addCriterion("USER_ID_NO like", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoNotLike(String value) {
            addCriterion("USER_ID_NO not like", value, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoIn(List<String> values) {
            addCriterion("USER_ID_NO in", values, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoNotIn(List<String> values) {
            addCriterion("USER_ID_NO not in", values, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoBetween(String value1, String value2) {
            addCriterion("USER_ID_NO between", value1, value2, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserIdNoNotBetween(String value1, String value2) {
            addCriterion("USER_ID_NO not between", value1, value2, "userIdNo");
            return (Criteria) this;
        }

        public Criteria andUserGenderIsNull() {
            addCriterion("USER_GENDER is null");
            return (Criteria) this;
        }

        public Criteria andUserGenderIsNotNull() {
            addCriterion("USER_GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andUserGenderEqualTo(String value) {
            addCriterion("USER_GENDER =", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderNotEqualTo(String value) {
            addCriterion("USER_GENDER <>", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderGreaterThan(String value) {
            addCriterion("USER_GENDER >", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderGreaterThanOrEqualTo(String value) {
            addCriterion("USER_GENDER >=", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderLessThan(String value) {
            addCriterion("USER_GENDER <", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderLessThanOrEqualTo(String value) {
            addCriterion("USER_GENDER <=", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderLike(String value) {
            addCriterion("USER_GENDER like", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderNotLike(String value) {
            addCriterion("USER_GENDER not like", value, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderIn(List<String> values) {
            addCriterion("USER_GENDER in", values, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderNotIn(List<String> values) {
            addCriterion("USER_GENDER not in", values, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderBetween(String value1, String value2) {
            addCriterion("USER_GENDER between", value1, value2, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserGenderNotBetween(String value1, String value2) {
            addCriterion("USER_GENDER not between", value1, value2, "userGender");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("USER_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("USER_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("USER_EMAIL =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("USER_EMAIL <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("USER_EMAIL >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("USER_EMAIL <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("USER_EMAIL <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("USER_EMAIL like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("USER_EMAIL not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("USER_EMAIL in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("USER_EMAIL not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("USER_EMAIL between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("USER_EMAIL not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayIsNull() {
            addCriterion("USER_BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayIsNotNull() {
            addCriterion("USER_BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("USER_BIRTHDAY =", value, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("USER_BIRTHDAY <>", value, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("USER_BIRTHDAY >", value, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("USER_BIRTHDAY >=", value, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("USER_BIRTHDAY <", value, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("USER_BIRTHDAY <=", value, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("USER_BIRTHDAY in", values, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("USER_BIRTHDAY not in", values, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("USER_BIRTHDAY between", value1, value2, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("USER_BIRTHDAY not between", value1, value2, "userBirthday");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNull() {
            addCriterion("USER_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNotNull() {
            addCriterion("USER_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressEqualTo(String value) {
            addCriterion("USER_ADDRESS =", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotEqualTo(String value) {
            addCriterion("USER_ADDRESS <>", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThan(String value) {
            addCriterion("USER_ADDRESS >", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ADDRESS >=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThan(String value) {
            addCriterion("USER_ADDRESS <", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThanOrEqualTo(String value) {
            addCriterion("USER_ADDRESS <=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLike(String value) {
            addCriterion("USER_ADDRESS like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotLike(String value) {
            addCriterion("USER_ADDRESS not like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressIn(List<String> values) {
            addCriterion("USER_ADDRESS in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotIn(List<String> values) {
            addCriterion("USER_ADDRESS not in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressBetween(String value1, String value2) {
            addCriterion("USER_ADDRESS between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotBetween(String value1, String value2) {
            addCriterion("USER_ADDRESS not between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserPostIsNull() {
            addCriterion("USER_POST is null");
            return (Criteria) this;
        }

        public Criteria andUserPostIsNotNull() {
            addCriterion("USER_POST is not null");
            return (Criteria) this;
        }

        public Criteria andUserPostEqualTo(String value) {
            addCriterion("USER_POST =", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostNotEqualTo(String value) {
            addCriterion("USER_POST <>", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostGreaterThan(String value) {
            addCriterion("USER_POST >", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostGreaterThanOrEqualTo(String value) {
            addCriterion("USER_POST >=", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostLessThan(String value) {
            addCriterion("USER_POST <", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostLessThanOrEqualTo(String value) {
            addCriterion("USER_POST <=", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostLike(String value) {
            addCriterion("USER_POST like", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostNotLike(String value) {
            addCriterion("USER_POST not like", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostIn(List<String> values) {
            addCriterion("USER_POST in", values, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostNotIn(List<String> values) {
            addCriterion("USER_POST not in", values, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostBetween(String value1, String value2) {
            addCriterion("USER_POST between", value1, value2, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostNotBetween(String value1, String value2) {
            addCriterion("USER_POST not between", value1, value2, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserTelIsNull() {
            addCriterion("USER_TEL is null");
            return (Criteria) this;
        }

        public Criteria andUserTelIsNotNull() {
            addCriterion("USER_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andUserTelEqualTo(String value) {
            addCriterion("USER_TEL =", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelNotEqualTo(String value) {
            addCriterion("USER_TEL <>", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelGreaterThan(String value) {
            addCriterion("USER_TEL >", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelGreaterThanOrEqualTo(String value) {
            addCriterion("USER_TEL >=", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelLessThan(String value) {
            addCriterion("USER_TEL <", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelLessThanOrEqualTo(String value) {
            addCriterion("USER_TEL <=", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelLike(String value) {
            addCriterion("USER_TEL like", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelNotLike(String value) {
            addCriterion("USER_TEL not like", value, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelIn(List<String> values) {
            addCriterion("USER_TEL in", values, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelNotIn(List<String> values) {
            addCriterion("USER_TEL not in", values, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelBetween(String value1, String value2) {
            addCriterion("USER_TEL between", value1, value2, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserTelNotBetween(String value1, String value2) {
            addCriterion("USER_TEL not between", value1, value2, "userTel");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNull() {
            addCriterion("USER_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andUserMobileIsNotNull() {
            addCriterion("USER_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andUserMobileEqualTo(String value) {
            addCriterion("USER_MOBILE =", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotEqualTo(String value) {
            addCriterion("USER_MOBILE <>", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThan(String value) {
            addCriterion("USER_MOBILE >", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileGreaterThanOrEqualTo(String value) {
            addCriterion("USER_MOBILE >=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThan(String value) {
            addCriterion("USER_MOBILE <", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLessThanOrEqualTo(String value) {
            addCriterion("USER_MOBILE <=", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileLike(String value) {
            addCriterion("USER_MOBILE like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotLike(String value) {
            addCriterion("USER_MOBILE not like", value, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileIn(List<String> values) {
            addCriterion("USER_MOBILE in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotIn(List<String> values) {
            addCriterion("USER_MOBILE not in", values, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileBetween(String value1, String value2) {
            addCriterion("USER_MOBILE between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserMobileNotBetween(String value1, String value2) {
            addCriterion("USER_MOBILE not between", value1, value2, "userMobile");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionIsNull() {
            addCriterion("USER_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionIsNotNull() {
            addCriterion("USER_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionEqualTo(String value) {
            addCriterion("USER_DESCRIPTION =", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionNotEqualTo(String value) {
            addCriterion("USER_DESCRIPTION <>", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionGreaterThan(String value) {
            addCriterion("USER_DESCRIPTION >", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("USER_DESCRIPTION >=", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionLessThan(String value) {
            addCriterion("USER_DESCRIPTION <", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionLessThanOrEqualTo(String value) {
            addCriterion("USER_DESCRIPTION <=", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionLike(String value) {
            addCriterion("USER_DESCRIPTION like", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionNotLike(String value) {
            addCriterion("USER_DESCRIPTION not like", value, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionIn(List<String> values) {
            addCriterion("USER_DESCRIPTION in", values, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionNotIn(List<String> values) {
            addCriterion("USER_DESCRIPTION not in", values, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionBetween(String value1, String value2) {
            addCriterion("USER_DESCRIPTION between", value1, value2, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserDescriptionNotBetween(String value1, String value2) {
            addCriterion("USER_DESCRIPTION not between", value1, value2, "userDescription");
            return (Criteria) this;
        }

        public Criteria andUserEnabledIsNull() {
            addCriterion("USER_ENABLED is null");
            return (Criteria) this;
        }

        public Criteria andUserEnabledIsNotNull() {
            addCriterion("USER_ENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andUserEnabledEqualTo(BigDecimal value) {
            addCriterion("USER_ENABLED =", value, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledNotEqualTo(BigDecimal value) {
            addCriterion("USER_ENABLED <>", value, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledGreaterThan(BigDecimal value) {
            addCriterion("USER_ENABLED >", value, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ENABLED >=", value, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledLessThan(BigDecimal value) {
            addCriterion("USER_ENABLED <", value, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ENABLED <=", value, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledIn(List<BigDecimal> values) {
            addCriterion("USER_ENABLED in", values, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledNotIn(List<BigDecimal> values) {
            addCriterion("USER_ENABLED not in", values, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ENABLED between", value1, value2, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserEnabledNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ENABLED not between", value1, value2, "userEnabled");
            return (Criteria) this;
        }

        public Criteria andUserLockedIsNull() {
            addCriterion("USER_LOCKED is null");
            return (Criteria) this;
        }

        public Criteria andUserLockedIsNotNull() {
            addCriterion("USER_LOCKED is not null");
            return (Criteria) this;
        }

        public Criteria andUserLockedEqualTo(BigDecimal value) {
            addCriterion("USER_LOCKED =", value, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedNotEqualTo(BigDecimal value) {
            addCriterion("USER_LOCKED <>", value, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedGreaterThan(BigDecimal value) {
            addCriterion("USER_LOCKED >", value, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_LOCKED >=", value, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedLessThan(BigDecimal value) {
            addCriterion("USER_LOCKED <", value, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_LOCKED <=", value, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedIn(List<BigDecimal> values) {
            addCriterion("USER_LOCKED in", values, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedNotIn(List<BigDecimal> values) {
            addCriterion("USER_LOCKED not in", values, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_LOCKED between", value1, value2, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserLockedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_LOCKED not between", value1, value2, "userLocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredIsNull() {
            addCriterion("USER_ACCOUNT_NONEXPIRED is null");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredIsNotNull() {
            addCriterion("USER_ACCOUNT_NONEXPIRED is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredEqualTo(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONEXPIRED =", value, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredNotEqualTo(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONEXPIRED <>", value, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredGreaterThan(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONEXPIRED >", value, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONEXPIRED >=", value, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredLessThan(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONEXPIRED <", value, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONEXPIRED <=", value, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredIn(List<BigDecimal> values) {
            addCriterion("USER_ACCOUNT_NONEXPIRED in", values, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredNotIn(List<BigDecimal> values) {
            addCriterion("USER_ACCOUNT_NONEXPIRED not in", values, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ACCOUNT_NONEXPIRED between", value1, value2, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonexpiredNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ACCOUNT_NONEXPIRED not between", value1, value2, "userAccountNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedIsNull() {
            addCriterion("USER_ACCOUNT_NONLOCKED is null");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedIsNotNull() {
            addCriterion("USER_ACCOUNT_NONLOCKED is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedEqualTo(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONLOCKED =", value, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedNotEqualTo(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONLOCKED <>", value, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedGreaterThan(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONLOCKED >", value, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONLOCKED >=", value, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedLessThan(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONLOCKED <", value, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ACCOUNT_NONLOCKED <=", value, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedIn(List<BigDecimal> values) {
            addCriterion("USER_ACCOUNT_NONLOCKED in", values, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedNotIn(List<BigDecimal> values) {
            addCriterion("USER_ACCOUNT_NONLOCKED not in", values, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ACCOUNT_NONLOCKED between", value1, value2, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserAccountNonlockedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ACCOUNT_NONLOCKED not between", value1, value2, "userAccountNonlocked");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredIsNull() {
            addCriterion("USER_CREDENTIALS_NONEXPIRED is null");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredIsNotNull() {
            addCriterion("USER_CREDENTIALS_NONEXPIRED is not null");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredEqualTo(BigDecimal value) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED =", value, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredNotEqualTo(BigDecimal value) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED <>", value, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredGreaterThan(BigDecimal value) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED >", value, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED >=", value, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredLessThan(BigDecimal value) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED <", value, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED <=", value, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredIn(List<BigDecimal> values) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED in", values, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredNotIn(List<BigDecimal> values) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED not in", values, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED between", value1, value2, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserCredentialsNonexpiredNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_CREDENTIALS_NONEXPIRED not between", value1, value2, "userCredentialsNonexpired");
            return (Criteria) this;
        }

        public Criteria andUserOrderIsNull() {
            addCriterion("USER_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andUserOrderIsNotNull() {
            addCriterion("USER_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andUserOrderEqualTo(BigDecimal value) {
            addCriterion("USER_ORDER =", value, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderNotEqualTo(BigDecimal value) {
            addCriterion("USER_ORDER <>", value, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderGreaterThan(BigDecimal value) {
            addCriterion("USER_ORDER >", value, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ORDER >=", value, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderLessThan(BigDecimal value) {
            addCriterion("USER_ORDER <", value, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ORDER <=", value, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderIn(List<BigDecimal> values) {
            addCriterion("USER_ORDER in", values, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderNotIn(List<BigDecimal> values) {
            addCriterion("USER_ORDER not in", values, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ORDER between", value1, value2, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserOrderNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ORDER not between", value1, value2, "userOrder");
            return (Criteria) this;
        }

        public Criteria andUserVersionIsNull() {
            addCriterion("USER_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andUserVersionIsNotNull() {
            addCriterion("USER_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andUserVersionEqualTo(BigDecimal value) {
            addCriterion("USER_VERSION =", value, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionNotEqualTo(BigDecimal value) {
            addCriterion("USER_VERSION <>", value, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionGreaterThan(BigDecimal value) {
            addCriterion("USER_VERSION >", value, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_VERSION >=", value, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionLessThan(BigDecimal value) {
            addCriterion("USER_VERSION <", value, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_VERSION <=", value, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionIn(List<BigDecimal> values) {
            addCriterion("USER_VERSION in", values, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionNotIn(List<BigDecimal> values) {
            addCriterion("USER_VERSION not in", values, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_VERSION between", value1, value2, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserVersionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_VERSION not between", value1, value2, "userVersion");
            return (Criteria) this;
        }

        public Criteria andUserCreatorIsNull() {
            addCriterion("USER_CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andUserCreatorIsNotNull() {
            addCriterion("USER_CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andUserCreatorEqualTo(String value) {
            addCriterion("USER_CREATOR =", value, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorNotEqualTo(String value) {
            addCriterion("USER_CREATOR <>", value, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorGreaterThan(String value) {
            addCriterion("USER_CREATOR >", value, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("USER_CREATOR >=", value, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorLessThan(String value) {
            addCriterion("USER_CREATOR <", value, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorLessThanOrEqualTo(String value) {
            addCriterion("USER_CREATOR <=", value, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorLike(String value) {
            addCriterion("USER_CREATOR like", value, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorNotLike(String value) {
            addCriterion("USER_CREATOR not like", value, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorIn(List<String> values) {
            addCriterion("USER_CREATOR in", values, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorNotIn(List<String> values) {
            addCriterion("USER_CREATOR not in", values, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorBetween(String value1, String value2) {
            addCriterion("USER_CREATOR between", value1, value2, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatorNotBetween(String value1, String value2) {
            addCriterion("USER_CREATOR not between", value1, value2, "userCreator");
            return (Criteria) this;
        }

        public Criteria andUserCreatedIsNull() {
            addCriterion("USER_CREATED is null");
            return (Criteria) this;
        }

        public Criteria andUserCreatedIsNotNull() {
            addCriterion("USER_CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andUserCreatedEqualTo(Date value) {
            addCriterion("USER_CREATED =", value, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedNotEqualTo(Date value) {
            addCriterion("USER_CREATED <>", value, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedGreaterThan(Date value) {
            addCriterion("USER_CREATED >", value, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_CREATED >=", value, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedLessThan(Date value) {
            addCriterion("USER_CREATED <", value, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedLessThanOrEqualTo(Date value) {
            addCriterion("USER_CREATED <=", value, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedIn(List<Date> values) {
            addCriterion("USER_CREATED in", values, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedNotIn(List<Date> values) {
            addCriterion("USER_CREATED not in", values, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedBetween(Date value1, Date value2) {
            addCriterion("USER_CREATED between", value1, value2, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserCreatedNotBetween(Date value1, Date value2) {
            addCriterion("USER_CREATED not between", value1, value2, "userCreated");
            return (Criteria) this;
        }

        public Criteria andUserModifierIsNull() {
            addCriterion("USER_MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andUserModifierIsNotNull() {
            addCriterion("USER_MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andUserModifierEqualTo(String value) {
            addCriterion("USER_MODIFIER =", value, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierNotEqualTo(String value) {
            addCriterion("USER_MODIFIER <>", value, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierGreaterThan(String value) {
            addCriterion("USER_MODIFIER >", value, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierGreaterThanOrEqualTo(String value) {
            addCriterion("USER_MODIFIER >=", value, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierLessThan(String value) {
            addCriterion("USER_MODIFIER <", value, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierLessThanOrEqualTo(String value) {
            addCriterion("USER_MODIFIER <=", value, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierLike(String value) {
            addCriterion("USER_MODIFIER like", value, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierNotLike(String value) {
            addCriterion("USER_MODIFIER not like", value, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierIn(List<String> values) {
            addCriterion("USER_MODIFIER in", values, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierNotIn(List<String> values) {
            addCriterion("USER_MODIFIER not in", values, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierBetween(String value1, String value2) {
            addCriterion("USER_MODIFIER between", value1, value2, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifierNotBetween(String value1, String value2) {
            addCriterion("USER_MODIFIER not between", value1, value2, "userModifier");
            return (Criteria) this;
        }

        public Criteria andUserModifiedIsNull() {
            addCriterion("USER_MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andUserModifiedIsNotNull() {
            addCriterion("USER_MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andUserModifiedEqualTo(Date value) {
            addCriterion("USER_MODIFIED =", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedNotEqualTo(Date value) {
            addCriterion("USER_MODIFIED <>", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedGreaterThan(Date value) {
            addCriterion("USER_MODIFIED >", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("USER_MODIFIED >=", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedLessThan(Date value) {
            addCriterion("USER_MODIFIED <", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedLessThanOrEqualTo(Date value) {
            addCriterion("USER_MODIFIED <=", value, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedIn(List<Date> values) {
            addCriterion("USER_MODIFIED in", values, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedNotIn(List<Date> values) {
            addCriterion("USER_MODIFIED not in", values, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedBetween(Date value1, Date value2) {
            addCriterion("USER_MODIFIED between", value1, value2, "userModified");
            return (Criteria) this;
        }

        public Criteria andUserModifiedNotBetween(Date value1, Date value2) {
            addCriterion("USER_MODIFIED not between", value1, value2, "userModified");
            return (Criteria) this;
        }

        public Criteria andAddvcdIsNull() {
            addCriterion("ADDVCD is null");
            return (Criteria) this;
        }

        public Criteria andAddvcdIsNotNull() {
            addCriterion("ADDVCD is not null");
            return (Criteria) this;
        }

        public Criteria andAddvcdEqualTo(String value) {
            addCriterion("ADDVCD =", value, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdNotEqualTo(String value) {
            addCriterion("ADDVCD <>", value, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdGreaterThan(String value) {
            addCriterion("ADDVCD >", value, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdGreaterThanOrEqualTo(String value) {
            addCriterion("ADDVCD >=", value, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdLessThan(String value) {
            addCriterion("ADDVCD <", value, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdLessThanOrEqualTo(String value) {
            addCriterion("ADDVCD <=", value, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdLike(String value) {
            addCriterion("ADDVCD like", value, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdNotLike(String value) {
            addCriterion("ADDVCD not like", value, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdIn(List<String> values) {
            addCriterion("ADDVCD in", values, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdNotIn(List<String> values) {
            addCriterion("ADDVCD not in", values, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdBetween(String value1, String value2) {
            addCriterion("ADDVCD between", value1, value2, "addvcd");
            return (Criteria) this;
        }

        public Criteria andAddvcdNotBetween(String value1, String value2) {
            addCriterion("ADDVCD not between", value1, value2, "addvcd");
            return (Criteria) this;
        }

        public Criteria andVisitsIsNull() {
            addCriterion("VISITS is null");
            return (Criteria) this;
        }

        public Criteria andVisitsIsNotNull() {
            addCriterion("VISITS is not null");
            return (Criteria) this;
        }

        public Criteria andVisitsEqualTo(BigDecimal value) {
            addCriterion("VISITS =", value, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsNotEqualTo(BigDecimal value) {
            addCriterion("VISITS <>", value, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsGreaterThan(BigDecimal value) {
            addCriterion("VISITS >", value, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VISITS >=", value, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsLessThan(BigDecimal value) {
            addCriterion("VISITS <", value, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VISITS <=", value, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsIn(List<BigDecimal> values) {
            addCriterion("VISITS in", values, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsNotIn(List<BigDecimal> values) {
            addCriterion("VISITS not in", values, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VISITS between", value1, value2, "visits");
            return (Criteria) this;
        }

        public Criteria andVisitsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VISITS not between", value1, value2, "visits");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNull() {
            addCriterion("LOGIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNotNull() {
            addCriterion("LOGIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeEqualTo(String value) {
            addCriterion("LOGIN_TIME =", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotEqualTo(String value) {
            addCriterion("LOGIN_TIME <>", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThan(String value) {
            addCriterion("LOGIN_TIME >", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_TIME >=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThan(String value) {
            addCriterion("LOGIN_TIME <", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_TIME <=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLike(String value) {
            addCriterion("LOGIN_TIME like", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotLike(String value) {
            addCriterion("LOGIN_TIME not like", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIn(List<String> values) {
            addCriterion("LOGIN_TIME in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotIn(List<String> values) {
            addCriterion("LOGIN_TIME not in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeBetween(String value1, String value2) {
            addCriterion("LOGIN_TIME between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotBetween(String value1, String value2) {
            addCriterion("LOGIN_TIME not between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNull() {
            addCriterion("LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLoginNameIsNotNull() {
            addCriterion("LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLoginNameEqualTo(String value) {
            addCriterion("LOGIN_NAME =", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotEqualTo(String value) {
            addCriterion("LOGIN_NAME <>", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThan(String value) {
            addCriterion("LOGIN_NAME >", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME >=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThan(String value) {
            addCriterion("LOGIN_NAME <", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_NAME <=", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameLike(String value) {
            addCriterion("LOGIN_NAME like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotLike(String value) {
            addCriterion("LOGIN_NAME not like", value, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameIn(List<String> values) {
            addCriterion("LOGIN_NAME in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotIn(List<String> values) {
            addCriterion("LOGIN_NAME not in", values, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME between", value1, value2, "loginName");
            return (Criteria) this;
        }

        public Criteria andLoginNameNotBetween(String value1, String value2) {
            addCriterion("LOGIN_NAME not between", value1, value2, "loginName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JEDA_USER
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 02 21:49:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JEDA_USER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}