package bas.jeda.dao;

import java.math.BigDecimal;
import java.util.Date;

public class JedaUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.POSITION_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.ORG_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_NAME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_PASSWORD
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_ID_NO
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_GENDER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_EMAIL
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_BIRTHDAY
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_ADDRESS
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_POST
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_TEL
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_MOBILE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_DESCRIPTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_ENABLED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private BigDecimal userEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_LOCKED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private BigDecimal userLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_ACCOUNT_NONEXPIRED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private BigDecimal userAccountNonexpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_ACCOUNT_NONLOCKED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private BigDecimal userAccountNonlocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_CREDENTIALS_NONEXPIRED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private BigDecimal userCredentialsNonexpired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_ORDER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private BigDecimal userOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_VERSION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private BigDecimal userVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_CREATOR
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userCreator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_CREATED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private Date userCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_MODIFIER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.USER_MODIFIED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private Date userModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.ADDVCD
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String addvcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.VISITS
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private BigDecimal visits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.LOGIN_TIME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_USER.LOGIN_NAME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String loginName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_ID
     *
     * @return the value of JEDA_USER.USER_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_ID
     *
     * @param userId the value for JEDA_USER.USER_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.POSITION_ID
     *
     * @return the value of JEDA_USER.POSITION_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.POSITION_ID
     *
     * @param positionId the value for JEDA_USER.POSITION_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setPositionId(String positionId) {
        this.positionId = positionId == null ? null : positionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.ORG_ID
     *
     * @return the value of JEDA_USER.ORG_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.ORG_ID
     *
     * @param orgId the value for JEDA_USER.ORG_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_NAME
     *
     * @return the value of JEDA_USER.USER_NAME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_NAME
     *
     * @param userName the value for JEDA_USER.USER_NAME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_PASSWORD
     *
     * @return the value of JEDA_USER.USER_PASSWORD
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_PASSWORD
     *
     * @param userPassword the value for JEDA_USER.USER_PASSWORD
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_ID_NO
     *
     * @return the value of JEDA_USER.USER_ID_NO
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserIdNo() {
        return userIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_ID_NO
     *
     * @param userIdNo the value for JEDA_USER.USER_ID_NO
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserIdNo(String userIdNo) {
        this.userIdNo = userIdNo == null ? null : userIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_GENDER
     *
     * @return the value of JEDA_USER.USER_GENDER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_GENDER
     *
     * @param userGender the value for JEDA_USER.USER_GENDER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_EMAIL
     *
     * @return the value of JEDA_USER.USER_EMAIL
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_EMAIL
     *
     * @param userEmail the value for JEDA_USER.USER_EMAIL
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_BIRTHDAY
     *
     * @return the value of JEDA_USER.USER_BIRTHDAY
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_BIRTHDAY
     *
     * @param userBirthday the value for JEDA_USER.USER_BIRTHDAY
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_ADDRESS
     *
     * @return the value of JEDA_USER.USER_ADDRESS
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_ADDRESS
     *
     * @param userAddress the value for JEDA_USER.USER_ADDRESS
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_POST
     *
     * @return the value of JEDA_USER.USER_POST
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserPost() {
        return userPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_POST
     *
     * @param userPost the value for JEDA_USER.USER_POST
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserPost(String userPost) {
        this.userPost = userPost == null ? null : userPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_TEL
     *
     * @return the value of JEDA_USER.USER_TEL
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_TEL
     *
     * @param userTel the value for JEDA_USER.USER_TEL
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_MOBILE
     *
     * @return the value of JEDA_USER.USER_MOBILE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_MOBILE
     *
     * @param userMobile the value for JEDA_USER.USER_MOBILE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_DESCRIPTION
     *
     * @return the value of JEDA_USER.USER_DESCRIPTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserDescription() {
        return userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_DESCRIPTION
     *
     * @param userDescription the value for JEDA_USER.USER_DESCRIPTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserDescription(String userDescription) {
        this.userDescription = userDescription == null ? null : userDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_ENABLED
     *
     * @return the value of JEDA_USER.USER_ENABLED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public BigDecimal getUserEnabled() {
        return userEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_ENABLED
     *
     * @param userEnabled the value for JEDA_USER.USER_ENABLED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserEnabled(BigDecimal userEnabled) {
        this.userEnabled = userEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_LOCKED
     *
     * @return the value of JEDA_USER.USER_LOCKED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public BigDecimal getUserLocked() {
        return userLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_LOCKED
     *
     * @param userLocked the value for JEDA_USER.USER_LOCKED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserLocked(BigDecimal userLocked) {
        this.userLocked = userLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_ACCOUNT_NONEXPIRED
     *
     * @return the value of JEDA_USER.USER_ACCOUNT_NONEXPIRED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public BigDecimal getUserAccountNonexpired() {
        return userAccountNonexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_ACCOUNT_NONEXPIRED
     *
     * @param userAccountNonexpired the value for JEDA_USER.USER_ACCOUNT_NONEXPIRED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserAccountNonexpired(BigDecimal userAccountNonexpired) {
        this.userAccountNonexpired = userAccountNonexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_ACCOUNT_NONLOCKED
     *
     * @return the value of JEDA_USER.USER_ACCOUNT_NONLOCKED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public BigDecimal getUserAccountNonlocked() {
        return userAccountNonlocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_ACCOUNT_NONLOCKED
     *
     * @param userAccountNonlocked the value for JEDA_USER.USER_ACCOUNT_NONLOCKED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserAccountNonlocked(BigDecimal userAccountNonlocked) {
        this.userAccountNonlocked = userAccountNonlocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_CREDENTIALS_NONEXPIRED
     *
     * @return the value of JEDA_USER.USER_CREDENTIALS_NONEXPIRED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public BigDecimal getUserCredentialsNonexpired() {
        return userCredentialsNonexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_CREDENTIALS_NONEXPIRED
     *
     * @param userCredentialsNonexpired the value for JEDA_USER.USER_CREDENTIALS_NONEXPIRED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserCredentialsNonexpired(BigDecimal userCredentialsNonexpired) {
        this.userCredentialsNonexpired = userCredentialsNonexpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_ORDER
     *
     * @return the value of JEDA_USER.USER_ORDER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public BigDecimal getUserOrder() {
        return userOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_ORDER
     *
     * @param userOrder the value for JEDA_USER.USER_ORDER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserOrder(BigDecimal userOrder) {
        this.userOrder = userOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_VERSION
     *
     * @return the value of JEDA_USER.USER_VERSION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public BigDecimal getUserVersion() {
        return userVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_VERSION
     *
     * @param userVersion the value for JEDA_USER.USER_VERSION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserVersion(BigDecimal userVersion) {
        this.userVersion = userVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_CREATOR
     *
     * @return the value of JEDA_USER.USER_CREATOR
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserCreator() {
        return userCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_CREATOR
     *
     * @param userCreator the value for JEDA_USER.USER_CREATOR
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserCreator(String userCreator) {
        this.userCreator = userCreator == null ? null : userCreator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_CREATED
     *
     * @return the value of JEDA_USER.USER_CREATED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public Date getUserCreated() {
        return userCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_CREATED
     *
     * @param userCreated the value for JEDA_USER.USER_CREATED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserCreated(Date userCreated) {
        this.userCreated = userCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_MODIFIER
     *
     * @return the value of JEDA_USER.USER_MODIFIER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserModifier() {
        return userModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_MODIFIER
     *
     * @param userModifier the value for JEDA_USER.USER_MODIFIER
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserModifier(String userModifier) {
        this.userModifier = userModifier == null ? null : userModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.USER_MODIFIED
     *
     * @return the value of JEDA_USER.USER_MODIFIED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public Date getUserModified() {
        return userModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.USER_MODIFIED
     *
     * @param userModified the value for JEDA_USER.USER_MODIFIED
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserModified(Date userModified) {
        this.userModified = userModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.ADDVCD
     *
     * @return the value of JEDA_USER.ADDVCD
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getAddvcd() {
        return addvcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.ADDVCD
     *
     * @param addvcd the value for JEDA_USER.ADDVCD
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setAddvcd(String addvcd) {
        this.addvcd = addvcd == null ? null : addvcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.VISITS
     *
     * @return the value of JEDA_USER.VISITS
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public BigDecimal getVisits() {
        return visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.VISITS
     *
     * @param visits the value for JEDA_USER.VISITS
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setVisits(BigDecimal visits) {
        this.visits = visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.LOGIN_TIME
     *
     * @return the value of JEDA_USER.LOGIN_TIME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.LOGIN_TIME
     *
     * @param loginTime the value for JEDA_USER.LOGIN_TIME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime == null ? null : loginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_USER.LOGIN_NAME
     *
     * @return the value of JEDA_USER.LOGIN_NAME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_USER.LOGIN_NAME
     *
     * @param loginName the value for JEDA_USER.LOGIN_NAME
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }
}