package bas.jeda.dao;

public class JedaRoleFunctionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_ROLE_FUNCTION.ROLE_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_ROLE_FUNCTION.FUNCTION_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String functionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_ROLE_FUNCTION.ROLE_ID
     *
     * @return the value of JEDA_ROLE_FUNCTION.ROLE_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_ROLE_FUNCTION.ROLE_ID
     *
     * @param roleId the value for JEDA_ROLE_FUNCTION.ROLE_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_ROLE_FUNCTION.FUNCTION_ID
     *
     * @return the value of JEDA_ROLE_FUNCTION.FUNCTION_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_ROLE_FUNCTION.FUNCTION_ID
     *
     * @param functionId the value for JEDA_ROLE_FUNCTION.FUNCTION_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId == null ? null : functionId.trim();
    }
}