package bas.jeda.dao;

import bas.jeda.dao.JedaModule;
import bas.jeda.dao.JedaModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JedaModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int countByExample(JedaModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int deleteByExample(JedaModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int deleteByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int insert(JedaModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int insertSelective(JedaModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    List<JedaModule> selectByExample(JedaModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    JedaModule selectByPrimaryKey(String moduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") JedaModule record, @Param("example") JedaModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int updateByExample(@Param("record") JedaModule record, @Param("example") JedaModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int updateByPrimaryKeySelective(JedaModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_MODULE
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int updateByPrimaryKey(JedaModule record);
}