package bas.jeda.dao;

import bas.jeda.dao.JedaRoleMenuExample;
import bas.jeda.dao.JedaRoleMenuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JedaRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_ROLE_MENU
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int countByExample(JedaRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_ROLE_MENU
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int deleteByExample(JedaRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_ROLE_MENU
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int deleteByPrimaryKey(JedaRoleMenuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_ROLE_MENU
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int insert(JedaRoleMenuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_ROLE_MENU
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int insertSelective(JedaRoleMenuKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_ROLE_MENU
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    List<JedaRoleMenuKey> selectByExample(JedaRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_ROLE_MENU
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") JedaRoleMenuKey record, @Param("example") JedaRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_ROLE_MENU
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    int updateByExample(@Param("record") JedaRoleMenuKey record, @Param("example") JedaRoleMenuExample example);
}