package bas.jeda.dao;

public class JedaRoleUserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_ROLE_USER.USER_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JEDA_ROLE_USER.ROLE_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_ROLE_USER.USER_ID
     *
     * @return the value of JEDA_ROLE_USER.USER_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_ROLE_USER.USER_ID
     *
     * @param userId the value for JEDA_ROLE_USER.USER_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JEDA_ROLE_USER.ROLE_ID
     *
     * @return the value of JEDA_ROLE_USER.ROLE_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JEDA_ROLE_USER.ROLE_ID
     *
     * @param roleId the value for JEDA_ROLE_USER.ROLE_ID
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}