package bas.jeda.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JedaFunctionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public JedaFunctionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFunctionIdIsNull() {
            addCriterion("FUNCTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andFunctionIdIsNotNull() {
            addCriterion("FUNCTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionIdEqualTo(String value) {
            addCriterion("FUNCTION_ID =", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdNotEqualTo(String value) {
            addCriterion("FUNCTION_ID <>", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdGreaterThan(String value) {
            addCriterion("FUNCTION_ID >", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCTION_ID >=", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdLessThan(String value) {
            addCriterion("FUNCTION_ID <", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdLessThanOrEqualTo(String value) {
            addCriterion("FUNCTION_ID <=", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdLike(String value) {
            addCriterion("FUNCTION_ID like", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdNotLike(String value) {
            addCriterion("FUNCTION_ID not like", value, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdIn(List<String> values) {
            addCriterion("FUNCTION_ID in", values, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdNotIn(List<String> values) {
            addCriterion("FUNCTION_ID not in", values, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdBetween(String value1, String value2) {
            addCriterion("FUNCTION_ID between", value1, value2, "functionId");
            return (Criteria) this;
        }

        public Criteria andFunctionIdNotBetween(String value1, String value2) {
            addCriterion("FUNCTION_ID not between", value1, value2, "functionId");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNull() {
            addCriterion("MODULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andModuleIdIsNotNull() {
            addCriterion("MODULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModuleIdEqualTo(String value) {
            addCriterion("MODULE_ID =", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotEqualTo(String value) {
            addCriterion("MODULE_ID <>", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThan(String value) {
            addCriterion("MODULE_ID >", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdGreaterThanOrEqualTo(String value) {
            addCriterion("MODULE_ID >=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThan(String value) {
            addCriterion("MODULE_ID <", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLessThanOrEqualTo(String value) {
            addCriterion("MODULE_ID <=", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdLike(String value) {
            addCriterion("MODULE_ID like", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotLike(String value) {
            addCriterion("MODULE_ID not like", value, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdIn(List<String> values) {
            addCriterion("MODULE_ID in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotIn(List<String> values) {
            addCriterion("MODULE_ID not in", values, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdBetween(String value1, String value2) {
            addCriterion("MODULE_ID between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andModuleIdNotBetween(String value1, String value2) {
            addCriterion("MODULE_ID not between", value1, value2, "moduleId");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIsNull() {
            addCriterion("FUNCTION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIsNotNull() {
            addCriterion("FUNCTION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionNameEqualTo(String value) {
            addCriterion("FUNCTION_NAME =", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotEqualTo(String value) {
            addCriterion("FUNCTION_NAME <>", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameGreaterThan(String value) {
            addCriterion("FUNCTION_NAME >", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCTION_NAME >=", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLessThan(String value) {
            addCriterion("FUNCTION_NAME <", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLessThanOrEqualTo(String value) {
            addCriterion("FUNCTION_NAME <=", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLike(String value) {
            addCriterion("FUNCTION_NAME like", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotLike(String value) {
            addCriterion("FUNCTION_NAME not like", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIn(List<String> values) {
            addCriterion("FUNCTION_NAME in", values, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotIn(List<String> values) {
            addCriterion("FUNCTION_NAME not in", values, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameBetween(String value1, String value2) {
            addCriterion("FUNCTION_NAME between", value1, value2, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotBetween(String value1, String value2) {
            addCriterion("FUNCTION_NAME not between", value1, value2, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlIsNull() {
            addCriterion("FUNCTION_URL is null");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlIsNotNull() {
            addCriterion("FUNCTION_URL is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlEqualTo(String value) {
            addCriterion("FUNCTION_URL =", value, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlNotEqualTo(String value) {
            addCriterion("FUNCTION_URL <>", value, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlGreaterThan(String value) {
            addCriterion("FUNCTION_URL >", value, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCTION_URL >=", value, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlLessThan(String value) {
            addCriterion("FUNCTION_URL <", value, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlLessThanOrEqualTo(String value) {
            addCriterion("FUNCTION_URL <=", value, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlLike(String value) {
            addCriterion("FUNCTION_URL like", value, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlNotLike(String value) {
            addCriterion("FUNCTION_URL not like", value, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlIn(List<String> values) {
            addCriterion("FUNCTION_URL in", values, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlNotIn(List<String> values) {
            addCriterion("FUNCTION_URL not in", values, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlBetween(String value1, String value2) {
            addCriterion("FUNCTION_URL between", value1, value2, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionUrlNotBetween(String value1, String value2) {
            addCriterion("FUNCTION_URL not between", value1, value2, "functionUrl");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeIsNull() {
            addCriterion("FUNCTION_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeIsNotNull() {
            addCriterion("FUNCTION_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeEqualTo(String value) {
            addCriterion("FUNCTION_TYPE =", value, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeNotEqualTo(String value) {
            addCriterion("FUNCTION_TYPE <>", value, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeGreaterThan(String value) {
            addCriterion("FUNCTION_TYPE >", value, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCTION_TYPE >=", value, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeLessThan(String value) {
            addCriterion("FUNCTION_TYPE <", value, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeLessThanOrEqualTo(String value) {
            addCriterion("FUNCTION_TYPE <=", value, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeLike(String value) {
            addCriterion("FUNCTION_TYPE like", value, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeNotLike(String value) {
            addCriterion("FUNCTION_TYPE not like", value, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeIn(List<String> values) {
            addCriterion("FUNCTION_TYPE in", values, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeNotIn(List<String> values) {
            addCriterion("FUNCTION_TYPE not in", values, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeBetween(String value1, String value2) {
            addCriterion("FUNCTION_TYPE between", value1, value2, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionTypeNotBetween(String value1, String value2) {
            addCriterion("FUNCTION_TYPE not between", value1, value2, "functionType");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionIsNull() {
            addCriterion("FUNCTION_HAS_PERMISSION is null");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionIsNotNull() {
            addCriterion("FUNCTION_HAS_PERMISSION is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_HAS_PERMISSION =", value, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionNotEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_HAS_PERMISSION <>", value, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionGreaterThan(BigDecimal value) {
            addCriterion("FUNCTION_HAS_PERMISSION >", value, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_HAS_PERMISSION >=", value, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionLessThan(BigDecimal value) {
            addCriterion("FUNCTION_HAS_PERMISSION <", value, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_HAS_PERMISSION <=", value, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionIn(List<BigDecimal> values) {
            addCriterion("FUNCTION_HAS_PERMISSION in", values, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionNotIn(List<BigDecimal> values) {
            addCriterion("FUNCTION_HAS_PERMISSION not in", values, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNCTION_HAS_PERMISSION between", value1, value2, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionHasPermissionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNCTION_HAS_PERMISSION not between", value1, value2, "functionHasPermission");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderIsNull() {
            addCriterion("FUNCTION_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderIsNotNull() {
            addCriterion("FUNCTION_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_ORDER =", value, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderNotEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_ORDER <>", value, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderGreaterThan(BigDecimal value) {
            addCriterion("FUNCTION_ORDER >", value, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_ORDER >=", value, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderLessThan(BigDecimal value) {
            addCriterion("FUNCTION_ORDER <", value, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_ORDER <=", value, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderIn(List<BigDecimal> values) {
            addCriterion("FUNCTION_ORDER in", values, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderNotIn(List<BigDecimal> values) {
            addCriterion("FUNCTION_ORDER not in", values, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNCTION_ORDER between", value1, value2, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionOrderNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNCTION_ORDER not between", value1, value2, "functionOrder");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyIsNull() {
            addCriterion("FUNCTION_READ_ONLY is null");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyIsNotNull() {
            addCriterion("FUNCTION_READ_ONLY is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_READ_ONLY =", value, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyNotEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_READ_ONLY <>", value, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyGreaterThan(BigDecimal value) {
            addCriterion("FUNCTION_READ_ONLY >", value, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_READ_ONLY >=", value, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyLessThan(BigDecimal value) {
            addCriterion("FUNCTION_READ_ONLY <", value, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_READ_ONLY <=", value, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyIn(List<BigDecimal> values) {
            addCriterion("FUNCTION_READ_ONLY in", values, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyNotIn(List<BigDecimal> values) {
            addCriterion("FUNCTION_READ_ONLY not in", values, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNCTION_READ_ONLY between", value1, value2, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionReadOnlyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNCTION_READ_ONLY not between", value1, value2, "functionReadOnly");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionIsNull() {
            addCriterion("FUNCTION_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionIsNotNull() {
            addCriterion("FUNCTION_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_VERSION =", value, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionNotEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_VERSION <>", value, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionGreaterThan(BigDecimal value) {
            addCriterion("FUNCTION_VERSION >", value, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_VERSION >=", value, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionLessThan(BigDecimal value) {
            addCriterion("FUNCTION_VERSION <", value, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FUNCTION_VERSION <=", value, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionIn(List<BigDecimal> values) {
            addCriterion("FUNCTION_VERSION in", values, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionNotIn(List<BigDecimal> values) {
            addCriterion("FUNCTION_VERSION not in", values, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNCTION_VERSION between", value1, value2, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionVersionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FUNCTION_VERSION not between", value1, value2, "functionVersion");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorIsNull() {
            addCriterion("FUNCTION_CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorIsNotNull() {
            addCriterion("FUNCTION_CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorEqualTo(String value) {
            addCriterion("FUNCTION_CREATOR =", value, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorNotEqualTo(String value) {
            addCriterion("FUNCTION_CREATOR <>", value, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorGreaterThan(String value) {
            addCriterion("FUNCTION_CREATOR >", value, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCTION_CREATOR >=", value, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorLessThan(String value) {
            addCriterion("FUNCTION_CREATOR <", value, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorLessThanOrEqualTo(String value) {
            addCriterion("FUNCTION_CREATOR <=", value, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorLike(String value) {
            addCriterion("FUNCTION_CREATOR like", value, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorNotLike(String value) {
            addCriterion("FUNCTION_CREATOR not like", value, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorIn(List<String> values) {
            addCriterion("FUNCTION_CREATOR in", values, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorNotIn(List<String> values) {
            addCriterion("FUNCTION_CREATOR not in", values, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorBetween(String value1, String value2) {
            addCriterion("FUNCTION_CREATOR between", value1, value2, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatorNotBetween(String value1, String value2) {
            addCriterion("FUNCTION_CREATOR not between", value1, value2, "functionCreator");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedIsNull() {
            addCriterion("FUNCTION_CREATED is null");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedIsNotNull() {
            addCriterion("FUNCTION_CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedEqualTo(Date value) {
            addCriterion("FUNCTION_CREATED =", value, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedNotEqualTo(Date value) {
            addCriterion("FUNCTION_CREATED <>", value, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedGreaterThan(Date value) {
            addCriterion("FUNCTION_CREATED >", value, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("FUNCTION_CREATED >=", value, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedLessThan(Date value) {
            addCriterion("FUNCTION_CREATED <", value, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedLessThanOrEqualTo(Date value) {
            addCriterion("FUNCTION_CREATED <=", value, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedIn(List<Date> values) {
            addCriterion("FUNCTION_CREATED in", values, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedNotIn(List<Date> values) {
            addCriterion("FUNCTION_CREATED not in", values, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedBetween(Date value1, Date value2) {
            addCriterion("FUNCTION_CREATED between", value1, value2, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionCreatedNotBetween(Date value1, Date value2) {
            addCriterion("FUNCTION_CREATED not between", value1, value2, "functionCreated");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierIsNull() {
            addCriterion("FUNCTION_MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierIsNotNull() {
            addCriterion("FUNCTION_MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierEqualTo(String value) {
            addCriterion("FUNCTION_MODIFIER =", value, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierNotEqualTo(String value) {
            addCriterion("FUNCTION_MODIFIER <>", value, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierGreaterThan(String value) {
            addCriterion("FUNCTION_MODIFIER >", value, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCTION_MODIFIER >=", value, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierLessThan(String value) {
            addCriterion("FUNCTION_MODIFIER <", value, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierLessThanOrEqualTo(String value) {
            addCriterion("FUNCTION_MODIFIER <=", value, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierLike(String value) {
            addCriterion("FUNCTION_MODIFIER like", value, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierNotLike(String value) {
            addCriterion("FUNCTION_MODIFIER not like", value, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierIn(List<String> values) {
            addCriterion("FUNCTION_MODIFIER in", values, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierNotIn(List<String> values) {
            addCriterion("FUNCTION_MODIFIER not in", values, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierBetween(String value1, String value2) {
            addCriterion("FUNCTION_MODIFIER between", value1, value2, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifierNotBetween(String value1, String value2) {
            addCriterion("FUNCTION_MODIFIER not between", value1, value2, "functionModifier");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedIsNull() {
            addCriterion("FUNCTION_MODIFIED is null");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedIsNotNull() {
            addCriterion("FUNCTION_MODIFIED is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedEqualTo(Date value) {
            addCriterion("FUNCTION_MODIFIED =", value, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedNotEqualTo(Date value) {
            addCriterion("FUNCTION_MODIFIED <>", value, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedGreaterThan(Date value) {
            addCriterion("FUNCTION_MODIFIED >", value, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("FUNCTION_MODIFIED >=", value, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedLessThan(Date value) {
            addCriterion("FUNCTION_MODIFIED <", value, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedLessThanOrEqualTo(Date value) {
            addCriterion("FUNCTION_MODIFIED <=", value, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedIn(List<Date> values) {
            addCriterion("FUNCTION_MODIFIED in", values, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedNotIn(List<Date> values) {
            addCriterion("FUNCTION_MODIFIED not in", values, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedBetween(Date value1, Date value2) {
            addCriterion("FUNCTION_MODIFIED between", value1, value2, "functionModified");
            return (Criteria) this;
        }

        public Criteria andFunctionModifiedNotBetween(Date value1, Date value2) {
            addCriterion("FUNCTION_MODIFIED not between", value1, value2, "functionModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 02 21:49:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JEDA_FUNCTION
     *
     * @mbggenerated Mon Mar 02 21:49:14 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}