package bas.jeda.dao;

import java.math.BigDecimal;

public class SCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_CODE.CODEID
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    private BigDecimal codeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_CODE.CODENO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    private String codeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_CODE.CODENAME
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    private String codename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_CODE.SORTNO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    private BigDecimal sortno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_CODE.PARENTCODENO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    private String parentcodeno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_CODE.CODEID
     *
     * @return the value of S_CODE.CODEID
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public BigDecimal getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_CODE.CODEID
     *
     * @param codeid the value for S_CODE.CODEID
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public void setCodeid(BigDecimal codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_CODE.CODENO
     *
     * @return the value of S_CODE.CODENO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public String getCodeno() {
        return codeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_CODE.CODENO
     *
     * @param codeno the value for S_CODE.CODENO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public void setCodeno(String codeno) {
        this.codeno = codeno == null ? null : codeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_CODE.CODENAME
     *
     * @return the value of S_CODE.CODENAME
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public String getCodename() {
        return codename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_CODE.CODENAME
     *
     * @param codename the value for S_CODE.CODENAME
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public void setCodename(String codename) {
        this.codename = codename == null ? null : codename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_CODE.SORTNO
     *
     * @return the value of S_CODE.SORTNO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public BigDecimal getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_CODE.SORTNO
     *
     * @param sortno the value for S_CODE.SORTNO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public void setSortno(BigDecimal sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_CODE.PARENTCODENO
     *
     * @return the value of S_CODE.PARENTCODENO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public String getParentcodeno() {
        return parentcodeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_CODE.PARENTCODENO
     *
     * @param parentcodeno the value for S_CODE.PARENTCODENO
     *
     * @mbggenerated Wed Mar 18 14:25:10 CST 2015
     */
    public void setParentcodeno(String parentcodeno) {
        this.parentcodeno = parentcodeno == null ? null : parentcodeno.trim();
    }
}