package bas.jeda.dao;

import bas.jeda.dao.SLog;
import bas.jeda.dao.SLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
/**2015.6.1
 * 日志
 * @author zhixiangfei
 */
public interface SLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int countByExample(SLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int deleteByExample(SLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int deleteByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int insert(SLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int insertSelective(SLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    List<SLog> selectByExample(SLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    SLog selectByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") SLog record, @Param("example") SLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int updateByExample(@Param("record") SLog record, @Param("example") SLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int updateByPrimaryKeySelective(SLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_LOG
     *
     * @mbggenerated Wed May 13 10:15:09 CST 2015
     */
    int updateByPrimaryKey(SLog record);
    
    
    public String selectmaxid();
}